var areainfo = [
		{sido:"서울",fullsido:"서울특별시", sub : [
										 {sigungu:"강남구"}
										,{sigungu:"강동구"}
										,{sigungu:"강북구"}
										,{sigungu:"강서구"}
										,{sigungu:"관악구"}
										,{sigungu:"광진구"}
										,{sigungu:"구로구"}
										,{sigungu:"금천구"}
										,{sigungu:"노원구"}
										,{sigungu:"도봉구"}
										,{sigungu:"동대문구"}
										,{sigungu:"동작구"}
										,{sigungu:"마포구"}
										,{sigungu:"서대문구"}
										,{sigungu:"서초구"}
										,{sigungu:"성동구"}
										,{sigungu:"성북구"}
										,{sigungu:"송파구"}
										,{sigungu:"양천구"}
										,{sigungu:"영등포구"}
										,{sigungu:"용산구"}
										,{sigungu:"은평구"}
										,{sigungu:"종로구"}
										,{sigungu:"중구"}
										,{sigungu:"중랑구"}
										]},
		{sido:"부산",fullsido:"부산광역시", sub:[
										 {sigungu:"강서구"}
										,{sigungu:"금정구"}
										,{sigungu:"기장군"}
										,{sigungu:"남구"}
										,{sigungu:"동구"}
										,{sigungu:"동래구"}
										,{sigungu:"부산진구"}
										,{sigungu:"북구"}
										,{sigungu:"사상구"}
										,{sigungu:"사하구"}
										,{sigungu:"서구"}
										,{sigungu:"수영구"}
										,{sigungu:"연제구"}
										,{sigungu:"영도구"}
										,{sigungu:"중구"}
										,{sigungu:"해운대구"}
										]},
		{sido:"대구",fullsido:"대구광역시",sub:[
										 {sigungu:"남구"}
										,{sigungu:"달서구"}
										,{sigungu:"달성군"}
										,{sigungu:"동구"}
										,{sigungu:"북구"}
										,{sigungu:"서구"}
										,{sigungu:"수성구"}
										,{sigungu:"중구"}
										]},
		{sido:"인천",fullsido:"인천광역시",sub:[
										 {sigungu:"강화군"}
										,{sigungu:"계양구"}
										,{sigungu:"남구"}
										,{sigungu:"남동구"}
										,{sigungu:"동구"}
										,{sigungu:"부평구"}
										,{sigungu:"서구"}
										,{sigungu:"연수구"}
										,{sigungu:"옹진군"}
										,{sigungu:"중구"}
										]},
		{sido:"광주",fullsido:"광주광역시",sub:[
										 {sigungu:"광산구"}
										,{sigungu:"남구"}
										,{sigungu:"동구"}
										,{sigungu:"북구"}
										,{sigungu:"서구"}
										]},
		{sido:"대전",fullsido:"대전광역시",sub:[
										 {sigungu:"대덕구"}
										,{sigungu:"동구"}
										,{sigungu:"서구"}
										,{sigungu:"유성구"}
										,{sigungu:"중구"}
										]},
		{sido:"울산",fullsido:"울산광역시",sub:[
										 {sigungu:"남구"}
										,{sigungu:"동구"}
										,{sigungu:"북구"}
										,{sigungu:"울주군"}
										,{sigungu:"중구"}
										]},
		{sido:"경기",fullsido:"경기도",sub:[
										 {sigungu:"가평군"}
										,{sigungu:"고양시"}
										,{sigungu:"과천시"}
										,{sigungu:"광명시"}
										,{sigungu:"광주시"}
										,{sigungu:"구리시"}
										,{sigungu:"군포시"}
										,{sigungu:"김포시"}
										,{sigungu:"남양주시"}
										,{sigungu:"동두천시"}
										,{sigungu:"부천시"}
										,{sigungu:"성남시"}
										,{sigungu:"수원시"}
										,{sigungu:"시흥시"}
										,{sigungu:"안산시"}
										,{sigungu:"안성시"}
										,{sigungu:"안양시"}
										,{sigungu:"양주시"}
										,{sigungu:"양평군"}
										,{sigungu:"여주시"}
										,{sigungu:"연천군"}
										,{sigungu:"오산시"}
										,{sigungu:"용인시"}
										,{sigungu:"의왕시"}
										,{sigungu:"의정부시"}
										,{sigungu:"이천시"}
										,{sigungu:"파주시"}
										,{sigungu:"평택시"}
										,{sigungu:"포천시"}
										,{sigungu:"하남시"}
										,{sigungu:"화성시"}
										]},
		{sido:"강원",fullsido:"강원도",sub:[
										 {sigungu:"강릉시"}
										,{sigungu:"고성군"}
										,{sigungu:"동해시"}
										,{sigungu:"삼척시"}
										,{sigungu:"속초시"}
										,{sigungu:"양구군"}
										,{sigungu:"양양군"}
										,{sigungu:"영월군"}
										,{sigungu:"원주시"}
										,{sigungu:"인제군"}
										,{sigungu:"정선군"}
										,{sigungu:"철원군"}
										,{sigungu:"춘천시"}
										,{sigungu:"태백시"}
										,{sigungu:"평창군"}
										,{sigungu:"홍천군"}
										,{sigungu:"화천군"}
										,{sigungu:"횡성군"}
									]},
		{sido:"충북",fullsido:"충청북도",sub:[
										 {sigungu:"괴산군"}
										,{sigungu:"단양군"}
										,{sigungu:"보은군"}
										,{sigungu:"영동군"}
										,{sigungu:"옥천군"}
										,{sigungu:"음성군"}
										,{sigungu:"제천시"}
										,{sigungu:"증평군"}
										,{sigungu:"진천군"}
										,{sigungu:"청주시"}
										,{sigungu:"충주시"}
									]},
		{sido:"충남",fullsido:"충청남도",sub:[
										 {sigungu:"계룡시"}
										,{sigungu:"공주시"}
										,{sigungu:"금산군"}
										,{sigungu:"논산시"}
										,{sigungu:"당진시"}
										,{sigungu:"보령시"}
										,{sigungu:"부여군"}
										,{sigungu:"서산시"}
										,{sigungu:"서천군"}
										,{sigungu:"아산시"}
										,{sigungu:"예산군"}
										,{sigungu:"천안시"}
										,{sigungu:"청양군"}
										,{sigungu:"태안군"}
										,{sigungu:"홍성군"}
										]},
		{sido:"전북",fullsido:"전라북도",sub:[
										 {sigungu:"고창군"}
										,{sigungu:"군산시"}
										,{sigungu:"김제시"}
										,{sigungu:"남원시"}
										,{sigungu:"무주군"}
										,{sigungu:"부안군"}
										,{sigungu:"순창군"}
										,{sigungu:"완주군"}
										,{sigungu:"익산시"}
										,{sigungu:"임실군"}
										,{sigungu:"장수군"}
										,{sigungu:"전주시"}
										,{sigungu:"정읍시"}
										,{sigungu:"진안군"}
										]},
		{sido:"전남",fullsido:"전라남도",sub:[
										 {sigungu:"강진군"}
										,{sigungu:"고흥군"}
										,{sigungu:"곡성군"}
										,{sigungu:"광양시"}
										,{sigungu:"구례군"}
										,{sigungu:"나주시"}
										,{sigungu:"담양군"}
										,{sigungu:"목포시"}
										,{sigungu:"무안군"}
										,{sigungu:"보성군"}
										,{sigungu:"순천시"}
										,{sigungu:"신안군"}
										,{sigungu:"여수시"}
										,{sigungu:"영광군"}
										,{sigungu:"영암군"}
										,{sigungu:"완도군"}
										,{sigungu:"장성군"}
										,{sigungu:"장흥군"}
										,{sigungu:"진도군"}
										,{sigungu:"함평군"}
										,{sigungu:"해남군"}
										,{sigungu:"화순군"}
										]},
		{sido:"경북",fullsido:"경상북도",sub:[
										 {sigungu:"경산시"}
										,{sigungu:"경주시"}
										,{sigungu:"고령군"}
										,{sigungu:"구미시"}
										,{sigungu:"군위군"}
										,{sigungu:"김천시"}
										,{sigungu:"문경시"}
										,{sigungu:"봉화군"}
										,{sigungu:"상주시"}
										,{sigungu:"성주군"}
										,{sigungu:"안동시"}
										,{sigungu:"영덕군"}
										,{sigungu:"영양군"}
										,{sigungu:"영주시"}
										,{sigungu:"영천시"}
										,{sigungu:"예천군"}
										,{sigungu:"울릉군"}
										,{sigungu:"울진군"}
										,{sigungu:"의성군"}
										,{sigungu:"청도군"}
										,{sigungu:"청송군"}
										,{sigungu:"칠곡군"}
										,{sigungu:"포항시"}
										]},
		{sido:"경남",fullsido:"경상남도",sub:[
										 {sigungu:"거제시"}
										,{sigungu:"거창군"}
										,{sigungu:"고성군"}
										,{sigungu:"김해시"}
										,{sigungu:"남해군"}
										,{sigungu:"밀양시"}
										,{sigungu:"사천시"}
										,{sigungu:"산청군"}
										,{sigungu:"양산시"}
										,{sigungu:"의령군"}
										,{sigungu:"진주시"}
										,{sigungu:"창녕군"}
										,{sigungu:"창원시"}
										,{sigungu:"통영시"}
										,{sigungu:"하동군"}
										,{sigungu:"함안군"}
										,{sigungu:"함양군"}
										,{sigungu:"합천군"}
										]},
		{sido:"제주",fullsido:"제주특별자치도",sub:[
										 {sigungu:"서귀포시"}
										,{sigungu:"제주시"}
										]},
		{sido:"세종",fullsido:"세종특별자치시",sub:[
										{sigungu:"가람동"}
										,{sigungu:"고운동"}
										,{sigungu:"금남면"}
										,{sigungu:"나성동"}
										,{sigungu:"다정동"}
										,{sigungu:"대평동"}
										,{sigungu:"도담동"}
										,{sigungu:"반곡동"}
										,{sigungu:"보람동"}
										,{sigungu:"부강면"}
										,{sigungu:"새롬동"}
										,{sigungu:"소담동"}
										,{sigungu:"소정면"}
										,{sigungu:"아름동"}
										,{sigungu:"어진동"}
										,{sigungu:"연기면"}
										,{sigungu:"연동면"}
										,{sigungu:"연서면"}
										,{sigungu:"장군면"}
										,{sigungu:"전동면"}
										,{sigungu:"전의면"}
										,{sigungu:"조치원읍"}
										,{sigungu:"종촌동"}
										,{sigungu:"한솔동"}
										]}
];

