var areainfo2 = [
		{gugun:"종로구", sub : [
{dong:"강남구"}
,{dong:"청운동"}
,{dong:"신교동"}
,{dong:"궁정동"}
,{dong:"효자동"}
,{dong:"창성동"}
,{dong:"통의동"}
,{dong:"적선동"}
,{dong:"통인동"}
,{dong:"누상동"}
,{dong:"옥인동"}
,{dong:"체부동"}
,{dong:"필운동"}
,{dong:"내자동"}
,{dong:"사직동"}
,{dong:"도렴동"}
,{dong:"당주동"}
,{dong:"내수동"}
,{dong:"세종로"}
,{dong:"신문로2가"}
,{dong:"청진동"}
,{dong:"서린동"}
,{dong:"수송동"}
,{dong:"중학동"}
,{dong:"종로1가"}
,{dong:"공평동"}
,{dong:"관훈동"}
,{dong:"견지동"}
,{dong:"권농동"}
,{dong:"운니동"}
,{dong:"익선동"}
,{dong:"경운동"}
,{dong:"관철동"}
,{dong:"인사동"}
,{dong:"낙원동"}
,{dong:"종로2가"}
,{dong:"팔판동"}
,{dong:"안국동"}
,{dong:"소격동"}
,{dong:"화동"}
,{dong:"사간동"}
,{dong:"송현동"}
,{dong:"가회동"}
,{dong:"재동"}
,{dong:"계동"}
,{dong:"원서동"}
,{dong:"묘동"}
,{dong:"봉익동"}
,{dong:"돈의동"}
,{dong:"장사동"}
,{dong:"관수동"}
,{dong:"종로3가"}
,{dong:"인의동"}
,{dong:"예지동"}
,{dong:"원남동"}
,{dong:"종로4가"}
,{dong:"효제동"}
,{dong:"종로5가"}
,{dong:"종로6가"}
,{dong:"이화동"}
,{dong:"연건동"}
,{dong:"충신동"}
,{dong:"동숭동"}
,{dong:"혜화동"}
,{dong:"명륜2가"}
,{dong:"명륜4가"}
,{dong:"명륜3가"}
,{dong:"창신동"}
,{dong:"숭인동"}
,{dong:"교남동"}
,{dong:"평동"}
,{dong:"송월동"}
,{dong:"홍파동"}
,{dong:"행촌동"}
,{dong:"구기동"}
,{dong:"평창동"}
,{dong:"부암동"}
,{dong:"홍지동"}
,{dong:"신영동"}
,{dong:"무악동"}]},
		{gugun:"중구", sub:[{dong:"무교동"}
,{dong:"다동"}
,{dong:"태평로1가"}
,{dong:"을지로1가"}
,{dong:"을지로2가"}
,{dong:"남대문로1가"}
,{dong:"삼각동"}
,{dong:"수하동"}
,{dong:"장교동"}
,{dong:"소공동"}
,{dong:"남창동"}
,{dong:"북창동"}
,{dong:"태평로2가"}
,{dong:"남대문로2가"}
,{dong:"남대문로3가"}
,{dong:"남대문로4가"}
,{dong:"남대문로5가"}
,{dong:"봉래동1가"}
,{dong:"회현동1가"}
,{dong:"회현동2가"}
,{dong:"회현동3가"}
,{dong:"충무로1가"}
,{dong:"충무로2가"}
,{dong:"명동1가"}
,{dong:"명동2가"}
,{dong:"남산동1가"}
,{dong:"남산동2가"}
,{dong:"저동1가"}
,{dong:"충무로4가"}
,{dong:"충무로5가"}
,{dong:"인현동2가"}
,{dong:"예관동"}
,{dong:"묵정동"}
,{dong:"필동1가"}
,{dong:"필동2가"}
,{dong:"필동3가"}
,{dong:"주자동"}
,{dong:"예장동"}
,{dong:"장충동1가"}
,{dong:"장충동2가"}
,{dong:"광희동1가"}
,{dong:"광희동2가"}
,{dong:"쌍림동"}
,{dong:"을지로6가"}
,{dong:"을지로7가"}
,{dong:"을지로5가"}
,{dong:"주교동"}
,{dong:"방산동"}
,{dong:"오장동"}
,{dong:"을지로3가"}
,{dong:"입정동"}
,{dong:"산림동"}
,{dong:"충무로3가"}
,{dong:"초동"}
,{dong:"저동2가"}
,{dong:"신당동"}
,{dong:"흥인동"}
,{dong:"무학동"}
,{dong:"황학동"}
,{dong:"서소문동"}
,{dong:"정동"}
,{dong:"순화동"}
,{dong:"의주로1가"}
,{dong:"중림동"}
,{dong:"의주로2가"}
,{dong:"만리동1가"}
,{dong:"만리동2가"}		]},
		{gugun:"용산구", sub:[{dong:"후암동"}
,{dong:"용산동2가"}
,{dong:"용산동4가"}
,{dong:"갈월동"}
,{dong:"남영동"}
,{dong:"용산동1가"}
,{dong:"동자동"}
,{dong:"서계동"}
,{dong:"청파동1가"}
,{dong:"청파동3가"}
,{dong:"원효로1가"}
,{dong:"원효로2가"}
,{dong:"신창동"}
,{dong:"산천동"}
,{dong:"청암동"}
,{dong:"원효로3가"}
,{dong:"원효로4가"}
,{dong:"효창동"}
,{dong:"용문동"}
,{dong:"문배동"}
,{dong:"신계동"}
,{dong:"한강로1가"}
,{dong:"한강로2가"}
,{dong:"용산동3가"}
,{dong:"용산동5가"}
,{dong:"한강로3가"}
,{dong:"이촌동"}
,{dong:"한남동"}
,{dong:"동빙고동"}
,{dong:"서빙고동"}
,{dong:"주성동"}
,{dong:"용산동6가"}
,{dong:"보광동"}		]},
		{gugun:"성동구", sub:[{dong:"상왕십리동"}
,{dong:"하왕십리동"}
,{dong:"홍익동"}
,{dong:"도선동"}
,{dong:"마장동"}
,{dong:"사근동"}
,{dong:"행당동"}
,{dong:"응봉동"}
,{dong:"금호동1가"}
,{dong:"금호동3가"}
,{dong:"금호동4가"}
,{dong:"옥수동"}
,{dong:"성수동1가"}
,{dong:"성수동2가"}
,{dong:"송정동"}
,{dong:"용답동"}		]},
		{gugun:"광진구", sub:[{dong:"중곡동"}
,{dong:"능동"}
,{dong:"구의동"}
,{dong:"광장동"}
,{dong:"자양동"}
,{dong:"화양동"}
,{dong:"군자동"}		]},
		{gugun:"동대문구", sub:[{dong:"신설동"}
,{dong:"용두동"}
,{dong:"제기동"}
,{dong:"전농동"}
,{dong:"답십리동"}
,{dong:"장안동"}
,{dong:"청량리동"}
,{dong:"회기동"}
,{dong:"휘경동"}
		]},
		{gugun:"중랑구", sub:[{dong:"면목동"}
,{dong:"상봉동"}
,{dong:"중화동"}
,{dong:"묵동"}
,{dong:"망우동"}
,{dong:"신내동"}
		]},
		{gugun:"성북구", sub:[{dong:"성북동"}
,{dong:"성북동1가"}
,{dong:"돈암동"}
,{dong:"동소문동1가"}
,{dong:"동소문동2가"}
,{dong:"동소문동3가"}
,{dong:"동소문동4가"}
,{dong:"동소문동5가"}
,{dong:"동소문동6가"}
,{dong:"삼선동1가"}
,{dong:"삼선동2가"}
,{dong:"삼선동3가"}
,{dong:"삼선동4가"}
,{dong:"삼선동5가"}
,{dong:"동선동1가"}
,{dong:"동선동2가"}
,{dong:"동선동3가"}
,{dong:"동선동4가"}
,{dong:"안암동1가"}
,{dong:"안암동2가"}
,{dong:"안암동3가"}
,{dong:"안암동4가"}
,{dong:"안암동5가"}
,{dong:"보문동4가"}
,{dong:"보문동5가"}
,{dong:"보문동6가"}
,{dong:"보문동7가"}
,{dong:"보문동2가"}
,{dong:"보문동3가"}
,{dong:"정릉동"}
,{dong:"길음동"}
,{dong:"종암동"}
,{dong:"하월곡동"}
,{dong:"상월곡동"}
,{dong:"장위동"}
,{dong:"석관동"}
		]},
		{gugun:"강북구", sub:[
{dong:"미아동"}
,{dong:"번동"}
,{dong:"수유동"}
,{dong:"우이동"}
		]},
		{gugun:"도봉구", sub:[
{dong:"쌍문동"}
,{dong:"방학동"}
,{dong:"창동"}
,{dong:"도봉동"}
		]},
		{gugun:"노원구", sub:[
{dong:"월계동"}
,{dong:"공릉동"}
,{dong:"하계동"}
,{dong:"상계동"}
,{dong:"중계동"}
		]},
		{gugun:"은평구", sub:[
{dong:"수색동"}
,{dong:"녹번동"}
,{dong:"불광동"}
,{dong:"갈현동"}
,{dong:"구산동"}
,{dong:"대조동"}
,{dong:"응암동"}
,{dong:"역촌동"}
,{dong:"신사동"}
,{dong:"진관동"}
		]},
		{gugun:"서대문구", sub:[
{dong:"충정로2가"}
,{dong:"충정로3가"}
,{dong:"합동"}
,{dong:"미근동"}
,{dong:"냉천동"}
,{dong:"천연동"}
,{dong:"옥천동"}
,{dong:"영천동"}
,{dong:"현저동"}
,{dong:"홍제동"}
,{dong:"대현동"}
,{dong:"대신동"}
,{dong:"신촌동"}
,{dong:"봉원동"}
,{dong:"창천동"}
,{dong:"연희동"}
,{dong:"홍은동"}
,{dong:"북가좌동"}
		]},
		{gugun:"마포구", sub:[
{dong:"아현동"}
,{dong:"공덕동"}
,{dong:"신공덕동"}
,{dong:"도화동"}
,{dong:"용강동"}
,{dong:"토정동"}
,{dong:"마포동"}
,{dong:"대흥동"}
,{dong:"염리동"}
,{dong:"신수동"}
,{dong:"현석동"}
,{dong:"구수동"}
,{dong:"창전동"}
,{dong:"상수동"}
,{dong:"하중동"}
,{dong:"신정동"}
,{dong:"당인동"}
,{dong:"동교동"}
,{dong:"합정동"}
,{dong:"망원동"}
,{dong:"연남동"}
,{dong:"성산동"}
,{dong:"중동"}
,{dong:"상암동"}
]},
		{gugun:"양천구", sub:[{dong:"신정동"}
,{dong:"목동"}
,{dong:"신월동"}
		]},
		{gugun:"강서구", sub:[
{dong:"염창동"}
,{dong:"등촌동"}
,{dong:"화곡동"}
,{dong:"가양동"}
,{dong:"마곡동"}
,{dong:"내발산동"}
,{dong:"외발산동"}
,{dong:"공항동"}
,{dong:"방화동"}
,{dong:"과해동"}
,{dong:"오곡동"}
,{dong:"오쇠동"}
		]},
		{gugun:"구로구", sub:[
{dong:"신도림동"}
,{dong:"구로동"}
,{dong:"가리봉동"}
,{dong:"고척동"}
,{dong:"개봉동"}
,{dong:"오류동"}
,{dong:"궁동"}
,{dong:"천왕동"}
,{dong:"항동"}
		]},
		{gugun:"금천구", sub:[
{dong:"가산동"}
,{dong:"독산동"}
,{dong:"시흥동"}
		]},
		{gugun:"영등포구", sub:[
{dong:"영등포동"}
,{dong:"영등포동1가"}
,{dong:"영등포동2가"}
,{dong:"영등포동3가"}
,{dong:"영등포동4가"}
,{dong:"영등포동5가"}
,{dong:"영등포동6가"}
,{dong:"영등포동7가"}
,{dong:"영등포동8가"}
,{dong:"당산동1가"}
,{dong:"당산동2가"}
,{dong:"당산동3가"}
,{dong:"당산동4가"}
,{dong:"당산동5가"}
,{dong:"당산동6가"}
,{dong:"당산동"}
,{dong:"도림동"}
,{dong:"문래동1가"}
,{dong:"문래동3가"}
,{dong:"문래동4가"}
,{dong:"문래동5가"}
,{dong:"문래동6가"}
,{dong:"양평동1가"}
,{dong:"양평동2가"}
,{dong:"양평동3가"}
,{dong:"양평동4가"}
,{dong:"양평동5가"}
,{dong:"양화동"}
,{dong:"신길동"}
,{dong:"대림동"}
,{dong:"양평동"}
		]},
		{gugun:"동작구", sub:[
{dong:"노량진동"}
,{dong:"상도동"}
,{dong:"상도1동"}
,{dong:"본동"}
,{dong:"흑석동"}
,{dong:"동작동"}
,{dong:"사당동"}
,{dong:"대방동"}
,{dong:"신대방동"}
		]},
		{gugun:"관악구", sub:[
{dong:"봉천동"}
,{dong:"신림동"}
,{dong:"남현동"}
		]},
		{gugun:"서초구", sub:[
{dong:"방배동"}
,{dong:"양재동"}
,{dong:"우면동"}
,{dong:"원지동"}
,{dong:"잠원동"}
,{dong:"반포동"}
,{dong:"서초동"}
,{dong:"내곡동"}
,{dong:"신원동"}
		]},
		{gugun:"강남구", sub:[
{dong:"역삼동"}
,{dong:"개포동"}
,{dong:"청담동"}
,{dong:"삼성동"}
,{dong:"대치동"}
,{dong:"신사동"}
,{dong:"논현동"}
,{dong:"세곡동"}
,{dong:"자곡동"}
,{dong:"율현동"}
,{dong:"일원동"}
,{dong:"수서동"}
,{dong:"도곡동"}
		]},
		{gugun:"송파구", sub:[
{dong:"잠실동"}
,{dong:"신천동"}
,{dong:"풍납동"}
,{dong:"송파동"}
,{dong:"석촌동"}
,{dong:"삼전동"}
,{dong:"가락동"}
,{dong:"문정동"}
,{dong:"장지동"}
,{dong:"방이동"}
,{dong:"오금동"}
,{dong:"거여동"}
,{dong:"마천동"}
		]},
		{gugun:"강동구", sub:[
{dong:"명일동"}
,{dong:"고덕동"}
,{dong:"상일동"}
,{dong:"길동"}
,{dong:"둔촌동"}
,{dong:"암사동"}
,{dong:"성내동"}
,{dong:"천호동"}
		]},
		{gugun:"중구", sub:[
{dong:"영주동"}
,{dong:"대창동1가"}
,{dong:"대창동2가"}
,{dong:"중앙동1가"}
,{dong:"중앙동2가"}
,{dong:"중앙동3가"}
,{dong:"중앙동4가"}
,{dong:"중앙동5가"}
,{dong:"중앙동6가"}
,{dong:"동광동1가"}
,{dong:"동광동2가"}
,{dong:"동광동3가"}
,{dong:"동광동4가"}
,{dong:"동광동5가"}
,{dong:"대청동1가"}
,{dong:"대청동2가"}
,{dong:"대청동3가"}
,{dong:"대청동4가"}
,{dong:"보수동2가"}
,{dong:"보수동3가"}
,{dong:"부평동1가"}
,{dong:"부평동2가"}
,{dong:"부평동3가"}
,{dong:"부평동4가"}
,{dong:"신창동1가"}
,{dong:"신창동2가"}
,{dong:"신창동3가"}
,{dong:"창선동1가"}
,{dong:"창선동2가"}
,{dong:"광복동1가"}
,{dong:"광복동2가"}
,{dong:"광복동3가"}
,{dong:"남포동1가"}
,{dong:"남포동2가"}
,{dong:"남포동3가"}
,{dong:"남포동4가"}
,{dong:"남포동6가"}
		]},
		{gugun:"서구", sub:[
{dong:"동대신동1가"}
,{dong:"동대신동2가"}
,{dong:"동대신동3가"}
,{dong:"서대신동1가"}
,{dong:"서대신동2가"}
,{dong:"서대신동3가"}
,{dong:"부용동1가"}
,{dong:"부용동2가"}
,{dong:"부민동1가"}
,{dong:"부민동3가"}
,{dong:"토성동1가"}
,{dong:"토성동2가"}
,{dong:"토성동3가"}
,{dong:"아미동1가"}
,{dong:"아미동2가"}
,{dong:"토성동4가"}
,{dong:"토성동5가"}
,{dong:"초장동"}
,{dong:"충무동2가"}
,{dong:"충무동3가"}
,{dong:"남부민동"}
,{dong:"암남동"}
		]},
		{gugun:"동구", sub:[
{dong:"초량동"}
,{dong:"수정동"}
,{dong:"좌천동"}
,{dong:"범일동"}
		]},
		{gugun:"영도구", sub:[
{dong:"대교동1가"}
,{dong:"대교동2가"}
,{dong:"대평동1가"}
,{dong:"대평동2가"}
,{dong:"남항동1가"}
,{dong:"남항동2가"}
,{dong:"남항동3가"}
,{dong:"영선동1가"}
,{dong:"영선동2가"}
,{dong:"영선동4가"}
,{dong:"신선동1가"}
,{dong:"신선동2가"}
,{dong:"신선동3가"}
,{dong:"봉래동1가"}
,{dong:"봉래동2가"}
,{dong:"봉래동3가"}
,{dong:"봉래동4가"}
,{dong:"봉래동5가"}
,{dong:"동삼동"}
		]},
		{gugun:"부산진구", sub:[
{dong:"양정동"}
,{dong:"전포동"}
,{dong:"부전동"}
,{dong:"범천동"}
,{dong:"범전동"}
,{dong:"연지동"}
,{dong:"초읍동"}
,{dong:"부암동"}
,{dong:"당감동"}
,{dong:"개금동"}
		]},
		{gugun:"동래구", sub:[
{dong:"명장동"}
,{dong:"안락동"}
,{dong:"칠산동"}
,{dong:"낙민동"}
,{dong:"복천동"}
,{dong:"수안동"}
,{dong:"명륜동"}
,{dong:"온천동"}
,{dong:"사직동"}
		]},
		{gugun:"남구", sub:[
{dong:"대연동"}
,{dong:"용호동"}
,{dong:"용당동"}
,{dong:"문현동"}
,{dong:"감만동"}
		]},
		{gugun:"북구", sub:[
{dong:"금곡동"}
,{dong:"화명동"}
,{dong:"만덕동"}
,{dong:"덕천동"}
,{dong:"구포동"}
		]},
		{gugun:"해운대구", sub:[
{dong:"반송동"}
,{dong:"석대동"}
,{dong:"반여동"}
,{dong:"재송동"}
,{dong:"우동"}
,{dong:"중동"}
,{dong:"좌동"}
,{dong:"송정동"}
		]},
		{gugun:"사하구", sub:[
{dong:"괴정동"}
,{dong:"당리동"}
,{dong:"하단동"}
,{dong:"신평동"}
,{dong:"장림동"}
,{dong:"다대동"}
,{dong:"구평동"}
,{dong:"감천동"}
		]},
		{gugun:"금정구", sub:[
{dong:"두구동"}
,{dong:"노포동"}
,{dong:"청룡동"}
,{dong:"남산동"}
,{dong:"선동"}
,{dong:"오륜동"}
,{dong:"구서동"}
,{dong:"장전동"}
,{dong:"부곡동"}
,{dong:"금사동"}
,{dong:"회동동"}
,{dong:"금성동"}
		]},
		{gugun:"강서구", sub:[
{dong:"대저1동"}
,{dong:"대저2동"}
,{dong:"강동동"}
,{dong:"명지동"}
,{dong:"죽림동"}
,{dong:"식만동"}
,{dong:"죽동동"}
,{dong:"봉림동"}
,{dong:"송정동"}
,{dong:"녹산동"}
,{dong:"생곡동"}
,{dong:"구랑동"}
,{dong:"지사동"}
,{dong:"미음동"}
,{dong:"범방동"}
,{dong:"신호동"}
,{dong:"동선동"}
,{dong:"성북동"}
,{dong:"천성동"}
,{dong:"대항동"}
		]},
		{gugun:"연제구", sub:[
{dong:"거제동"}
,{dong:"연산동"}
		]},
		{gugun:"수영구", sub:[
{dong:"망미동"}
,{dong:"수영동"}
,{dong:"민락동"}
,{dong:"광안동"}
,{dong:"남천동"}
		]},
		{gugun:"사상구", sub:[
{dong:"삼락동"}
,{dong:"모라동"}
,{dong:"덕포동"}
,{dong:"괘법동"}
,{dong:"감전동"}
,{dong:"주례동"}
,{dong:"학장동"}
,{dong:"엄궁동"}
		]},
		{gugun:"기장군", sub:[
{dong:"장안읍"}
,{dong:"정관읍"}
		]},
		{gugun:"중구", sub:[
{dong:"동인동1가"}
,{dong:"동인동2가"}
,{dong:"동인동3가"}
,{dong:"동인동4가"}
,{dong:"삼덕동1가"}
,{dong:"삼덕동2가"}
,{dong:"삼덕동3가"}
,{dong:"봉산동"}
,{dong:"장관동"}
,{dong:"수동"}
,{dong:"덕산동"}
,{dong:"종로1가"}
,{dong:"종로2가"}
,{dong:"사일동"}
,{dong:"동일동"}
,{dong:"남일동"}
,{dong:"전동"}
,{dong:"동성로3가"}
,{dong:"문화동"}
,{dong:"공평동"}
,{dong:"동성로2가"}
,{dong:"태평로1가"}
,{dong:"교동"}
,{dong:"용덕동"}
,{dong:"상덕동"}
,{dong:"완전동"}
,{dong:"도원동"}
,{dong:"태평로3가"}
,{dong:"인교동"}
,{dong:"서야동"}
,{dong:"서성로1가"}
,{dong:"시장북로"}
,{dong:"하서동"}
,{dong:"남성로"}
,{dong:"계산동1가"}
,{dong:"계산동2가"}
,{dong:"서문로2가"}
,{dong:"서성로2가"}
,{dong:"포정동"}
,{dong:"서문로1가"}
,{dong:"서내동"}
,{dong:"북성로2가"}
,{dong:"대안동"}
,{dong:"동성로1가"}
,{dong:"태평로2가"}
,{dong:"화전동"}
,{dong:"향촌동"}
,{dong:"북내동"}
,{dong:"대신동"}
,{dong:"달성동"}
,{dong:"남산동"}
,{dong:"대봉동"}
		]},
		{gugun:"동구", sub:[
{dong:"신암동"}
,{dong:"신천동"}
,{dong:"효목동"}
,{dong:"평광동"}
,{dong:"봉무동"}
,{dong:"불로동"}
,{dong:"도동"}
,{dong:"지저동"}
,{dong:"입석동"}
,{dong:"방촌동"}
,{dong:"둔산동"}
,{dong:"부동"}
,{dong:"신평동"}
,{dong:"서호동"}
,{dong:"동호동"}
,{dong:"신기동"}
,{dong:"율하동"}
,{dong:"용계동"}
,{dong:"상매동"}
,{dong:"매여동"}
,{dong:"각산동"}
,{dong:"신서동"}
,{dong:"동내동"}
,{dong:"괴전동"}
,{dong:"금강동"}
,{dong:"대림동"}
,{dong:"사복동"}
,{dong:"내곡동"}
,{dong:"능성동"}
,{dong:"진인동"}
,{dong:"도학동"}
,{dong:"백안동"}
,{dong:"미곡동"}
,{dong:"용수동"}
,{dong:"신무동"}
,{dong:"미대동"}
,{dong:"신용동"}
,{dong:"중대동"}
,{dong:"송정동"}
,{dong:"덕곡동"}
,{dong:"지묘동"}
		]},
		{gugun:"서구", sub:[
{dong:"내당동"}
,{dong:"비산동"}
,{dong:"평리동"}
,{dong:"상리동"}
,{dong:"중리동"}
,{dong:"이현동"}
,{dong:"원대동1가"}
,{dong:"원대동2가"}
,{dong:"원대동3가"}
		]},
		{gugun:"남구", sub:[
{dong:"이천동"}
,{dong:"봉덕동"}
,{dong:"대명동"}
		]},
		{gugun:"북구", sub:[
{dong:"칠성동1가"}
,{dong:"칠성동2가"}
,{dong:"고성동1가"}
,{dong:"고성동2가"}
,{dong:"고성동3가"}
,{dong:"침산동"}
,{dong:"노원동1가"}
,{dong:"노원동2가"}
,{dong:"노원동3가"}
,{dong:"산격동"}
,{dong:"복현동"}
,{dong:"검단동"}
,{dong:"동변동"}
,{dong:"서변동"}
,{dong:"조야동"}
,{dong:"노곡동"}
,{dong:"읍내동"}
,{dong:"동호동"}
,{dong:"도남동"}
,{dong:"국우동"}
,{dong:"구암동"}
,{dong:"동천동"}
,{dong:"관음동"}
,{dong:"태전동"}
,{dong:"매천동"}
,{dong:"팔달동"}
,{dong:"금호동"}
,{dong:"연경동"}
		]},
		{gugun:"수성구", sub:[
{dong:"범어동"}
,{dong:"만촌동"}
,{dong:"수성동1가"}
,{dong:"수성동2가"}
,{dong:"수성동3가"}
,{dong:"수성동4가"}
,{dong:"황금동"}
,{dong:"중동"}
,{dong:"상동"}
,{dong:"두산동"}
,{dong:"지산동"}
,{dong:"범물동"}
,{dong:"시지동"}
,{dong:"매호동"}
,{dong:"성동"}
,{dong:"사월동"}
,{dong:"신매동"}
,{dong:"욱수동"}
,{dong:"삼덕동"}
,{dong:"연호동"}
,{dong:"이천동"}
,{dong:"고모동"}
,{dong:"가천동"}
,{dong:"대흥동"}
		]},
		{gugun:"달서구", sub:[
{dong:"성당동"}
,{dong:"두류동"}
,{dong:"파호동"}
,{dong:"호림동"}
,{dong:"갈산동"}
,{dong:"신당동"}
,{dong:"이곡동"}
,{dong:"장동"}
,{dong:"용산동"}
,{dong:"죽전동"}
,{dong:"감삼동"}
,{dong:"본리동"}
,{dong:"상인동"}
,{dong:"도원동"}
,{dong:"진천동"}
,{dong:"유천동"}
,{dong:"대천동"}
,{dong:"월암동"}
,{dong:"송현동"}
,{dong:"대곡동"}
,{dong:"본동"}
,{dong:"호산동"}
		]},
		{gugun:"달성군", sub:[
{dong:"논공읍"}
,{dong:"다사읍"}
		]},
		{gugun:"중구", sub:[
{dong:"중앙동1가"}
,{dong:"중앙동2가"}
,{dong:"중앙동3가"}
,{dong:"중앙동4가"}
,{dong:"해안동1가"}
,{dong:"해안동2가"}
,{dong:"해안동3가"}
,{dong:"해안동4가"}
,{dong:"관동1가"}
,{dong:"관동3가"}
,{dong:"항동1가"}
,{dong:"항동2가"}
,{dong:"항동3가"}
,{dong:"항동4가"}
,{dong:"항동5가"}
,{dong:"항동6가"}
,{dong:"항동7가"}
,{dong:"송학동1가"}
,{dong:"송학동3가"}
,{dong:"사동"}
,{dong:"신생동"}
,{dong:"신포동"}
,{dong:"답동"}
,{dong:"신흥동1가"}
,{dong:"신흥동2가"}
,{dong:"신흥동3가"}
,{dong:"선화동"}
,{dong:"율목동"}
,{dong:"도원동"}
,{dong:"내동"}
,{dong:"경동"}
,{dong:"용동"}
,{dong:"인현동"}
,{dong:"전동"}
,{dong:"북성동1가"}
,{dong:"북성동2가"}
,{dong:"선린동"}
,{dong:"송월동1가"}
,{dong:"송월동2가"}
,{dong:"송월동3가"}
,{dong:"중산동"}
,{dong:"운남동"}
,{dong:"운서동"}
,{dong:"운북동"}
,{dong:"을왕동"}
,{dong:"덕교동"}
,{dong:"무의동"}
		]},
		{gugun:"동구", sub:[
{dong:"만석동"}
,{dong:"화수동"}
,{dong:"송현동"}
,{dong:"화평동"}
,{dong:"창영동"}
,{dong:"금곡동"}
,{dong:"송림동"}
		]},
		{gugun:"남구", sub:[
{dong:"숭의동"}
,{dong:"용현동"}
,{dong:"학익동"}
,{dong:"도화동"}
,{dong:"주안동"}
,{dong:"관교동"}
,{dong:"문학동"}
		]},
		{gugun:"연수구", sub:[
{dong:"옥련동"}
,{dong:"선학동"}
,{dong:"연수동"}
,{dong:"청학동"}
,{dong:"동춘동"}
,{dong:"송도동"}
		]},
		{gugun:"남동구", sub:[
{dong:"구월동"}
,{dong:"간석동"}
,{dong:"만수동"}
,{dong:"장수동"}
,{dong:"서창동"}
,{dong:"운연동"}
,{dong:"남촌동"}
,{dong:"수산동"}
,{dong:"도림동"}
,{dong:"고잔동"}
		]},
		{gugun:"부평구", sub:[
{dong:"부평동"}
,{dong:"십정동"}
,{dong:"산곡동"}
,{dong:"청천동"}
,{dong:"삼산동"}
,{dong:"갈산동"}
,{dong:"부개동"}
,{dong:"일신동"}
,{dong:"구산동"}
		]},
		{gugun:"계양구", sub:[
{dong:"효성동"}
,{dong:"계산동"}
,{dong:"작전동"}
,{dong:"서운동"}
,{dong:"임학동"}
,{dong:"용종동"}
,{dong:"병방동"}
,{dong:"방축동"}
,{dong:"박촌동"}
,{dong:"귤현동"}
,{dong:"상야동"}
,{dong:"하야동"}
,{dong:"평동"}
,{dong:"노오지동"}
,{dong:"선주지동"}
,{dong:"이화동"}
,{dong:"오류동"}
,{dong:"갈현동"}
,{dong:"목상동"}
,{dong:"다남동"}
,{dong:"장기동"}
		]},
		{gugun:"서구", sub:[
{dong:"서구"}
,{dong:"시천동"}
,{dong:"검암동"}
,{dong:"경서동"}
,{dong:"공촌동"}
,{dong:"연희동"}
,{dong:"심곡동"}
,{dong:"가정동"}
,{dong:"신현동"}
,{dong:"원창동"}
,{dong:"가좌동"}
,{dong:"마전동"}
,{dong:"당하동"}
,{dong:"원당동"}
,{dong:"대곡동"}
,{dong:"금곡동"}
,{dong:"오류동"}
,{dong:"불로동"}
		]},
		{gugun:"동구", sub:[
{dong:"대인동"}
,{dong:"금남로5가"}
,{dong:"충장로5가"}
,{dong:"수기동"}
,{dong:"대의동"}
,{dong:"궁동"}
,{dong:"장동"}
,{dong:"동명동"}
,{dong:"계림동"}
,{dong:"지산동"}
,{dong:"남동"}
,{dong:"광산동"}
,{dong:"금동"}
,{dong:"호남동"}
,{dong:"불로동"}
,{dong:"황금동"}
,{dong:"서석동"}
,{dong:"소태동"}
,{dong:"운림동"}
,{dong:"학동"}
,{dong:"월남동"}
,{dong:"선교동"}
,{dong:"내남동"}
,{dong:"용산동"}
,{dong:"충장로1가"}
,{dong:"충장로2가"}
,{dong:"충장로3가"}
,{dong:"금남로1가"}
,{dong:"금남로2가"}
,{dong:"금남로3가"}
,{dong:"금남로4가"}
		]},
		{gugun:"서구", sub:[
{dong:"양동"}
,{dong:"농성동"}
,{dong:"광천동"}
,{dong:"유촌동"}
,{dong:"덕흥동"}
,{dong:"쌍촌동"}
,{dong:"화정동"}
,{dong:"내방동"}
,{dong:"서창동"}
,{dong:"세하동"}
,{dong:"용두동"}
,{dong:"풍암동"}
,{dong:"벽진동"}
,{dong:"마륵동"}
,{dong:"매월동"}
,{dong:"동천동"}
		]},
		{gugun:"남구", sub:[
{dong:"사동"}
,{dong:"구동"}
,{dong:"서동"}
,{dong:"월산동"}
,{dong:"백운동"}
,{dong:"주월동"}
,{dong:"노대동"}
,{dong:"진월동"}
,{dong:"덕남동"}
,{dong:"임암동"}
,{dong:"송하동"}
,{dong:"양림동"}
,{dong:"방림동"}
,{dong:"봉선동"}
,{dong:"구소동"}
,{dong:"양촌동"}
,{dong:"도금동"}
,{dong:"승촌동"}
,{dong:"압촌동"}
,{dong:"화장동"}
,{dong:"칠석동"}
,{dong:"석정동"}
,{dong:"신장동"}
,{dong:"양과동"}
,{dong:"이장동"}
,{dong:"대지동"}
,{dong:"원산동"}
		]},
		{gugun:"북구", sub:[
{dong:"중흥동"}
,{dong:"유동"}
,{dong:"누문동"}
,{dong:"북동"}
,{dong:"임동"}
,{dong:"신안동"}
,{dong:"용봉동"}
,{dong:"동림동"}
,{dong:"운암동"}
,{dong:"풍향동"}
,{dong:"문흥동"}
,{dong:"각화동"}
,{dong:"두암동"}
,{dong:"오치동"}
,{dong:"삼각동"}
,{dong:"매곡동"}
,{dong:"충효동"}
,{dong:"덕의동"}
,{dong:"망월동"}
,{dong:"청풍동"}
,{dong:"화암동"}
,{dong:"장등동"}
,{dong:"운정동"}
,{dong:"본촌동"}
,{dong:"일곡동"}
,{dong:"양산동"}
,{dong:"연제동"}
,{dong:"용두동"}
,{dong:"지야동"}
,{dong:"태령동"}
,{dong:"수곡동"}
,{dong:"효령동"}
,{dong:"용전동"}
,{dong:"용강동"}
,{dong:"생용동"}
,{dong:"월출동"}
,{dong:"오룡동"}
		]},
		{gugun:"광산구", sub:[
{dong:"송정동"}
,{dong:"도산동"}
,{dong:"도호동"}
,{dong:"신촌동"}
,{dong:"서봉동"}
,{dong:"운수동"}
,{dong:"선암동"}
,{dong:"소촌동"}
,{dong:"우산동"}
,{dong:"박호동"}
,{dong:"비아동"}
,{dong:"도천동"}
,{dong:"수완동"}
,{dong:"월계동"}
,{dong:"쌍암동"}
,{dong:"산월동"}
,{dong:"신창동"}
,{dong:"신가동"}
,{dong:"안청동"}
,{dong:"진곡동"}
,{dong:"장덕동"}
,{dong:"흑석동"}
,{dong:"하남동"}
,{dong:"장수동"}
,{dong:"산정동"}
,{dong:"월곡동"}
,{dong:"등임동"}
,{dong:"고룡동"}
,{dong:"신룡동"}
,{dong:"두정동"}
,{dong:"임곡동"}
,{dong:"광산동"}
,{dong:"오산동"}
,{dong:"사호동"}
,{dong:"하산동"}
,{dong:"유계동"}
,{dong:"용봉동"}
,{dong:"요기동"}
,{dong:"복룡동"}
,{dong:"송대동"}
,{dong:"옥동"}
,{dong:"월전동"}
,{dong:"장록동"}
,{dong:"송촌동"}
,{dong:"지죽동"}
,{dong:"용곡동"}
,{dong:"지정동"}
,{dong:"명화동"}
,{dong:"동산동"}
,{dong:"연산동"}
,{dong:"도덕동"}
,{dong:"송산동"}
,{dong:"지평동"}
,{dong:"오운동"}
,{dong:"양동"}
,{dong:"내산동"}
,{dong:"대산동"}
,{dong:"송학동"}
,{dong:"신동"}
,{dong:"삼도동"}
,{dong:"남산동"}
,{dong:"송치동"}
,{dong:"산수동"}
,{dong:"지산동"}
,{dong:"왕동"}
,{dong:"북산동"}
,{dong:"명도동"}
,{dong:"동호동"}
,{dong:"덕림동"}
,{dong:"양산동"}
,{dong:"동림동"}
,{dong:"오선동"}
		]},
		{gugun:"동구", sub:[
{dong:"원동"}
,{dong:"인동"}
,{dong:"효동"}
,{dong:"천동"}
,{dong:"가오동"}
,{dong:"신흥동"}
,{dong:"판암동"}
,{dong:"삼정동"}
,{dong:"용운동"}
,{dong:"자양동"}
,{dong:"신안동"}
,{dong:"소제동"}
,{dong:"가양동"}
,{dong:"용전동"}
,{dong:"성남동"}
,{dong:"홍도동"}
,{dong:"삼성동"}
,{dong:"정동"}
,{dong:"추동"}
,{dong:"비룡동"}
,{dong:"주산동"}
,{dong:"용계동"}
,{dong:"마산동"}
,{dong:"효평동"}
,{dong:"직동"}
,{dong:"세천동"}
,{dong:"신상동"}
,{dong:"신촌동"}
,{dong:"사성동"}
,{dong:"내탑동"}
,{dong:"오동"}
,{dong:"주촌동"}
,{dong:"낭월동"}
,{dong:"대별동"}
,{dong:"이사동"}
,{dong:"대성동"}
,{dong:"소호동"}
,{dong:"구도동"}
,{dong:"삼괴동"}
,{dong:"상소동"}
,{dong:"하소동"}
		]},
		{gugun:"중구", sub:[
{dong:"은행동"}
,{dong:"선화동"}
,{dong:"목동"}
,{dong:"중촌동"}
,{dong:"대흥동"}
,{dong:"문창동"}
,{dong:"석교동"}
,{dong:"호동"}
,{dong:"옥계동"}
,{dong:"부사동"}
,{dong:"용두동"}
,{dong:"오류동"}
,{dong:"태평동"}
,{dong:"유천동"}
,{dong:"문화동"}
,{dong:"산성동"}
,{dong:"사정동"}
,{dong:"안영동"}
,{dong:"구완동"}
,{dong:"침산동"}
,{dong:"목달동"}
,{dong:"정생동"}
,{dong:"어남동"}
,{dong:"금동"}
		]},
		{gugun:"서구", sub:[
{dong:"복수동"}
,{dong:"변동"}
,{dong:"도마동"}
,{dong:"정림동"}
,{dong:"용문동"}
,{dong:"탄방동"}
,{dong:"괴정동"}
,{dong:"가장동"}
,{dong:"갈마동"}
,{dong:"둔산동"}
,{dong:"월평동"}
,{dong:"가수원동"}
,{dong:"도안동"}
,{dong:"관저동"}
,{dong:"흑석동"}
,{dong:"매노동"}
,{dong:"산직동"}
,{dong:"평촌동"}
,{dong:"오동"}
,{dong:"우명동"}
,{dong:"원정동"}
,{dong:"용촌동"}
,{dong:"봉곡동"}
,{dong:"괴곡동"}
,{dong:"만년동"}
		]},
		{gugun:"유성구", sub:[
{dong:"원내동"}
,{dong:"교촌동"}
,{dong:"대정동"}
,{dong:"용계동"}
,{dong:"학하동"}
,{dong:"계산동"}
,{dong:"성북동"}
,{dong:"세동"}
,{dong:"송정동"}
,{dong:"봉명동"}
,{dong:"구암동"}
,{dong:"덕명동"}
,{dong:"원신흥동"}
,{dong:"상대동"}
,{dong:"복용동"}
,{dong:"장대동"}
,{dong:"갑동"}
,{dong:"노은동"}
,{dong:"죽동"}
,{dong:"궁동"}
,{dong:"어은동"}
,{dong:"구성동"}
,{dong:"신성동"}
,{dong:"가정동"}
,{dong:"도룡동"}
,{dong:"장동"}
,{dong:"방현동"}
,{dong:"덕진동"}
,{dong:"하기동"}
,{dong:"추목동"}
,{dong:"자운동"}
,{dong:"신봉동"}
,{dong:"수남동"}
,{dong:"안산동"}
,{dong:"외삼동"}
,{dong:"반석동"}
,{dong:"전민동"}
,{dong:"원촌동"}
,{dong:"탑립동"}
,{dong:"용산동"}
,{dong:"봉산동"}
,{dong:"관평동"}
,{dong:"송강동"}
,{dong:"금고동"}
,{dong:"대동"}
,{dong:"신동"}
,{dong:"둔곡동"}
,{dong:"구룡동"}
		]},
		{gugun:"대덕구", sub:[{dong:"오정동"}
,{dong:"대화동"}
,{dong:"읍내동"}
,{dong:"연축동"}
,{dong:"신대동"}
,{dong:"와동"}
,{dong:"송촌동"}
,{dong:"법동"}
,{dong:"중리동"}
,{dong:"석봉동"}
,{dong:"목상동"}
,{dong:"문평동"}
,{dong:"신일동"}
,{dong:"덕암동"}
,{dong:"상서동"}
,{dong:"평촌동"}
,{dong:"장동"}
,{dong:"용호동"}
,{dong:"갈전동"}
,{dong:"부수동"}
,{dong:"황호동"}
,{dong:"삼정동"}
,{dong:"미호동"}
,{dong:"신탄진동"}
		]},
		{gugun:"중구", sub:[
{dong:"학성동"}
,{dong:"학산동"}
,{dong:"복산동"}
,{dong:"북정동"}
,{dong:"옥교동"}
,{dong:"성남동"}
,{dong:"교동"}
,{dong:"우정동"}
,{dong:"성안동"}
,{dong:"태화동"}
,{dong:"다운동"}
,{dong:"동동"}
,{dong:"서동"}
,{dong:"남외동"}
,{dong:"장현동"}
,{dong:"약사동"}
,{dong:"반구동"}
		]},
		{gugun:"남구", sub:[
{dong:"무거동"}
,{dong:"옥동"}
,{dong:"두왕동"}
,{dong:"신정동"}
,{dong:"달동"}
,{dong:"삼산동"}
,{dong:"여천동"}
,{dong:"야음동"}
,{dong:"선암동"}
,{dong:"부곡동"}
,{dong:"고사동"}
,{dong:"성암동"}
,{dong:"황성동"}
,{dong:"용연동"}
,{dong:"남화동"}
,{dong:"용잠동"}
,{dong:"장생포동"}
,{dong:"매암동"}
		]},
		{gugun:"동구", sub:[
{dong:"방어동"}
,{dong:"화정동"}
,{dong:"일산동"}
,{dong:"전하동"}
,{dong:"미포동"}
,{dong:"주전동"}
,{dong:"동부동"}
,{dong:"서부동"}
		]},
		{gugun:"북구", sub:[
{dong:"창평동"}
,{dong:"호계동"}
,{dong:"매곡동"}
,{dong:"가대동"}
,{dong:"신천동"}
,{dong:"중산동"}
,{dong:"상안동"}
,{dong:"천곡동"}
,{dong:"달천동"}
,{dong:"무룡동"}
,{dong:"구유동"}
,{dong:"정자동"}
,{dong:"신명동"}
,{dong:"대안동"}
,{dong:"당사동"}
,{dong:"신현동"}
,{dong:"산하동"}
,{dong:"어물동"}
,{dong:"진장동"}
,{dong:"연암동"}
,{dong:"효문동"}
,{dong:"양정동"}
,{dong:"화봉동"}
,{dong:"송정동"}
,{dong:"염포동"}
		]},
		{gugun:"울주군", sub:[
{dong:"언양읍"}
,{dong:"온양읍"}
,{dong:"범서읍"}
		]},
		{gugun:"세종특별자치시", sub:[
{dong:"반곡동"}
,{dong:"소담동"}
,{dong:"보람동"}
,{dong:"대평동"}
,{dong:"가람동"}
,{dong:"한솔동"}
,{dong:"나성동"}
,{dong:"새롬동"}
,{dong:"다정동"}
,{dong:"종촌동"}
,{dong:"고운동"}
,{dong:"아름동"}
,{dong:"도담동"}
,{dong:"조치원읍"}
,{dong:"연기면"}
,{dong:"연동면"}
,{dong:"부강면"}
,{dong:"금남면"}
,{dong:"장군면"}
,{dong:"연서면"}
,{dong:"전의면"}
,{dong:"전동면"}
,{dong:"소정면"}
		]},
		{gugun:"의정부시", sub:[
{dong:"의정부동"}
,{dong:"호원동"}
,{dong:"장암동"}
,{dong:"신곡동"}
,{dong:"용현동"}
,{dong:"민락동"}
,{dong:"낙양동"}
,{dong:"자일동"}
,{dong:"금오동"}
,{dong:"녹양동"}
,{dong:"고산동"}
,{dong:"산곡동"}
		]},
		{gugun:"부천시", sub:[
{dong:"원미동"}
,{dong:"심곡동"}
,{dong:"춘의동"}
,{dong:"도당동"}
,{dong:"약대동"}
,{dong:"소사동"}
,{dong:"역곡동"}
,{dong:"중동"}
,{dong:"상동"}
,{dong:"심곡본동"}
,{dong:"범박동"}
,{dong:"괴안동"}
,{dong:"송내동"}
,{dong:"옥길동"}
,{dong:"계수동"}
,{dong:"오정동"}
,{dong:"여월동"}
,{dong:"작동"}
,{dong:"고강동"}
,{dong:"대장동"}
,{dong:"삼정동"}
,{dong:"내동"}
		]},
		{gugun:"광명시", sub:[
{dong:"광명동"}
,{dong:"철산동"}
,{dong:"하안동"}
,{dong:"소하동"}
,{dong:"노온사동"}
,{dong:"일직동"}
,{dong:"가학동"}
,{dong:"옥길동"}
		]},
		{gugun:"평택시", sub:[
{dong:"서정동"}
,{dong:"장당동"}
,{dong:"모곡동"}
,{dong:"칠괴동"}
,{dong:"칠원동"}
,{dong:"도일동"}
,{dong:"가재동"}
,{dong:"장안동"}
,{dong:"이충동"}
,{dong:"독곡동"}
,{dong:"신장동"}
,{dong:"평택동"}
,{dong:"통복동"}
,{dong:"군문동"}
,{dong:"유천동"}
,{dong:"합정동"}
,{dong:"비전동"}
,{dong:"동삭동"}
,{dong:"지제동"}
,{dong:"신대동"}
,{dong:"소사동"}
,{dong:"용이동"}
,{dong:"월곡동"}
,{dong:"청룡동"}
,{dong:"죽백동"}
,{dong:"안중읍"}
,{dong:"포승읍"}
,{dong:"청북읍"}
		]},
		{gugun:"동두천시", sub:[
{dong:"송내동"}
,{dong:"지행동"}
,{dong:"생연동"}
,{dong:"광암동"}
,{dong:"걸산동"}
,{dong:"보산동"}
,{dong:"동두천동"}
,{dong:"안흥동"}
,{dong:"상봉암동"}
,{dong:"탑동동"}
,{dong:"상패동"}
		]},
		{gugun:"과천시", sub:[
{dong:"관문동"}
,{dong:"문원동"}
,{dong:"갈현동"}
,{dong:"막계동"}
,{dong:"과천동"}
,{dong:"주암동"}
,{dong:"중앙동"}
,{dong:"원문동"}
,{dong:"별양동"}
		]},
		{gugun:"구리시", sub:[
{dong:"갈매동"}
,{dong:"사노동"}
,{dong:"인창동"}
,{dong:"교문동"}
,{dong:"수택동"}
,{dong:"아천동"}
,{dong:"토평동"}
		]},
		{gugun:"남양주시", sub:[
{dong:"호평동"}
,{dong:"평내동"}
,{dong:"금곡동"}
,{dong:"일패동"}
,{dong:"이패동"}
,{dong:"삼패동"}
,{dong:"가운동"}
,{dong:"수석동"}
,{dong:"지금동"}
,{dong:"별내동"}
,{dong:"진접읍"}
,{dong:"화도읍"}
,{dong:"진건읍"}
,{dong:"오남읍"}
		]},
		{gugun:"오산시", sub:[
{dong:"오산동"}
,{dong:"부산동"}
,{dong:"원동"}
,{dong:"궐동"}
,{dong:"청학동"}
,{dong:"가장동"}
,{dong:"금암동"}
,{dong:"수청동"}
,{dong:"은계동"}
,{dong:"외삼미동"}
,{dong:"양산동"}
,{dong:"세교동"}
,{dong:"지곶동"}
,{dong:"서랑동"}
,{dong:"서동"}
,{dong:"벌음동"}
,{dong:"두곡동"}
,{dong:"탑동"}
,{dong:"가수동"}
,{dong:"고현동"}
,{dong:"청호동"}
,{dong:"갈곶동"}
		]},
		{gugun:"시흥시", sub:[
{dong:"대야동"}
,{dong:"신천동"}
,{dong:"방산동"}
,{dong:"포동"}
,{dong:"미산동"}
,{dong:"은행동"}
,{dong:"안현동"}
,{dong:"매화동"}
,{dong:"도창동"}
,{dong:"과림동"}
,{dong:"계수동"}
,{dong:"화정동"}
,{dong:"능곡동"}
,{dong:"하중동"}
,{dong:"광석동"}
,{dong:"물왕동"}
,{dong:"산현동"}
,{dong:"조남동"}
,{dong:"논곡동"}
,{dong:"목감동"}
,{dong:"거모동"}
,{dong:"군자동"}
,{dong:"장현동"}
,{dong:"월곶동"}
,{dong:"정왕동"}
,{dong:"죽율동"}
,{dong:"무지내동"}
		]},
		{gugun:"군포시", sub:[
{dong:"당동"}
,{dong:"당정동"}
,{dong:"부곡동"}
,{dong:"산본동"}
,{dong:"금정동"}
,{dong:"둔대동"}
,{dong:"속달동"}
,{dong:"대야미동"}
,{dong:"도마교동"}
		]},
		{gugun:"의왕시", sub:[
{dong:"고천동"}
,{dong:"이동"}
,{dong:"삼동"}
,{dong:"왕곡동"}
,{dong:"오전동"}
,{dong:"학의동"}
,{dong:"내손동"}
,{dong:"청계동"}
,{dong:"포일동"}
,{dong:"초평동"}
		]},
		{gugun:"하남시", sub:[
{dong:"천현동"}
,{dong:"하산곡동"}
,{dong:"창우동"}
,{dong:"배알미동"}
,{dong:"상산곡동"}
,{dong:"신장동"}
,{dong:"당정동"}
,{dong:"덕풍동"}
,{dong:"망월동"}
,{dong:"미사동"}
,{dong:"선동"}
,{dong:"감북동"}
,{dong:"감일동"}
,{dong:"감이동"}
,{dong:"학암동"}
,{dong:"교산동"}
,{dong:"춘궁동"}
,{dong:"하사창동"}
,{dong:"항동"}
,{dong:"초일동"}
,{dong:"초이동"}
,{dong:"광암동"}
		]},
		{gugun:"파주시", sub:[
{dong:"금촌동"}
,{dong:"아동동"}
,{dong:"야동동"}
,{dong:"검산동"}
,{dong:"맥금동"}
,{dong:"교하동"}
,{dong:"야당동"}
,{dong:"다율동"}
,{dong:"상지석동"}
,{dong:"산남동"}
,{dong:"동패동"}
,{dong:"당하동"}
,{dong:"문발동"}
,{dong:"송촌동"}
,{dong:"목동동"}
,{dong:"하지석동"}
,{dong:"서패동"}
,{dong:"연다산동"}
,{dong:"와동동"}
,{dong:"금릉동"}
,{dong:"파주읍"}
,{dong:"법원읍"}
,{dong:"조리읍"}
		]},
		{gugun:"이천시", sub:[
{dong:"창전동"}
,{dong:"관고동"}
,{dong:"중리동"}
,{dong:"증일동"}
,{dong:"율현동"}
,{dong:"진리동"}
,{dong:"안흥동"}
,{dong:"갈산동"}
,{dong:"증포동"}
,{dong:"사음동"}
,{dong:"단월동"}
,{dong:"대포동"}
,{dong:"고담동"}
,{dong:"장록동"}
,{dong:"부발읍"}
		]},
		{gugun:"안성시", sub:[
{dong:"봉산동"}
,{dong:"숭인동"}
,{dong:"영동"}
,{dong:"봉남동"}
,{dong:"구포동"}
,{dong:"동본동"}
,{dong:"명륜동"}
,{dong:"옥천동"}
,{dong:"낙원동"}
,{dong:"성남동"}
,{dong:"신흥동"}
,{dong:"인지동"}
,{dong:"금산동"}
,{dong:"연지동"}
,{dong:"대천동"}
,{dong:"서인동"}
,{dong:"석정동"}
,{dong:"아양동"}
,{dong:"계동"}
,{dong:"옥산동"}
,{dong:"사곡동"}
,{dong:"도기동"}
,{dong:"당왕동"}
,{dong:"가사동"}
,{dong:"가현동"}
,{dong:"신건지동"}
,{dong:"신소현동"}
,{dong:"현수동"}
,{dong:"발화동"}
,{dong:"중리동"}
		]},
		{gugun:"김포시", sub:[
{dong:"북변동"}
,{dong:"걸포동"}
,{dong:"운양동"}
,{dong:"장기동"}
,{dong:"감정동"}
,{dong:"사우동"}
,{dong:"풍무동"}
,{dong:"마산동"}
,{dong:"구래동"}
,{dong:"고촌읍"}
,{dong:"양촌읍"}
		]},
		{gugun:"화성시", sub:[
{dong:"진안동"}
,{dong:"병점동"}
,{dong:"능동"}
,{dong:"기산동"}
,{dong:"반정동"}
,{dong:"황계동"}
,{dong:"배양동"}
,{dong:"기안동"}
,{dong:"송산동"}
,{dong:"안녕동"}
,{dong:"반송동"}
,{dong:"석우동"}
,{dong:"오산동"}
,{dong:"영천동"}
,{dong:"봉담읍"}
,{dong:"우정읍"}
,{dong:"향남읍"}
,{dong:"남양읍"}
		]},
		{gugun:"광주시", sub:[
{dong:"경안동"}
,{dong:"쌍령동"}
,{dong:"송정동"}
,{dong:"회덕동"}
,{dong:"탄벌동"}
,{dong:"목현동"}
,{dong:"삼동"}
,{dong:"중대동"}
,{dong:"직동"}
,{dong:"장지동"}
,{dong:"역동"}
,{dong:"목동"}
,{dong:"초월읍"}
,{dong:"곤지암읍"}
		]},
		{gugun:"양주시", sub:[
{dong:"유양동"}
,{dong:"어둔동"}
,{dong:"남방동"}
,{dong:"마전동"}
,{dong:"산북동"}
,{dong:"광사동"}
,{dong:"만송동"}
,{dong:"삼숭동"}
,{dong:"고읍동"}
,{dong:"봉양동"}
,{dong:"회암동"}
,{dong:"율정동"}
,{dong:"옥정동"}
,{dong:"고암동"}
,{dong:"덕계동"}
,{dong:"회정동"}
		]},
		{gugun:"포천시", sub:[
{dong:"신읍동"}
,{dong:"어룡동"}
,{dong:"자작동"}
,{dong:"선단동"}
,{dong:"설운동"}
,{dong:"동교동"}
		]},
		{gugun:"여주시", sub:[
{dong:"상동"}
,{dong:"홍문동"}
,{dong:"창동"}
,{dong:"우만동"}
,{dong:"단현동"}
,{dong:"신진동"}
,{dong:"하동"}
,{dong:"교동"}
,{dong:"월송동"}
,{dong:"연라동"}
,{dong:"상거동"}
,{dong:"하거동"}
,{dong:"삼교동"}
,{dong:"점봉동"}
,{dong:"능현동"}
,{dong:"멱곡동"}
,{dong:"연양동"}
,{dong:"매룡동"}
,{dong:"오학동"}
,{dong:"현암동"}
,{dong:"오금동"}
		]},
		{gugun:"연천군", sub:[
{dong:"전곡읍"}
		]},
		{gugun:"가평군", sub:[
{dong:"청평면"}
,{dong:"조종면"}
		]},
		{gugun:"양평군", sub:[
{dong:"지평면"}
		]},
		{gugun:"춘천시", sub:[
{dong:"봉의동"}
,{dong:"요선동"}
,{dong:"낙원동"}
,{dong:"중앙로1가"}
,{dong:"중앙로2가"}
,{dong:"중앙로3가"}
,{dong:"옥천동"}
,{dong:"조양동"}
,{dong:"죽림동"}
,{dong:"약사동"}
,{dong:"효자동"}
,{dong:"소양로1가"}
,{dong:"소양로2가"}
,{dong:"소양로3가"}
,{dong:"소양로4가"}
,{dong:"근화동"}
,{dong:"우두동"}
,{dong:"사농동"}
,{dong:"온의동"}
,{dong:"교동"}
,{dong:"퇴계동"}
,{dong:"석사동"}
,{dong:"삼천동"}
,{dong:"칠전동"}
,{dong:"송암동"}
,{dong:"신동"}
,{dong:"중도동"}
		]},
		{gugun:"원주시", sub:[
{dong:"중앙동"}
,{dong:"평원동"}
,{dong:"원동"}
,{dong:"인동"}
,{dong:"개운동"}
,{dong:"명륜동"}
,{dong:"단구동"}
,{dong:"일산동"}
,{dong:"학성동"}
,{dong:"우산동"}
,{dong:"태장동"}
,{dong:"봉산동"}
,{dong:"행구동"}
,{dong:"무실동"}
,{dong:"관설동"}
,{dong:"반곡동"}
,{dong:"가현동"}
		]},
		{gugun:"강릉시", sub:[
{dong:"홍제동"}
,{dong:"남문동"}
,{dong:"명주동"}
,{dong:"성내동"}
,{dong:"임당동"}
,{dong:"금학동"}
,{dong:"용강동"}
,{dong:"성남동"}
,{dong:"옥천동"}
,{dong:"포남동"}
,{dong:"초당동"}
,{dong:"강문동"}
,{dong:"송정동"}
,{dong:"견소동"}
,{dong:"내곡동"}
,{dong:"회산동"}
,{dong:"장현동"}
,{dong:"박월동"}
,{dong:"노암동"}
,{dong:"유산동"}
,{dong:"월호평동"}
,{dong:"신석동"}
,{dong:"입암동"}
,{dong:"청량동"}
,{dong:"두산동"}
,{dong:"학동"}
,{dong:"병산동"}
,{dong:"유천동"}
,{dong:"지변동"}
,{dong:"죽헌동"}
,{dong:"대전동"}
,{dong:"운정동"}
,{dong:"난곡동"}
,{dong:"저동"}
,{dong:"안현동"}
,{dong:"운산동"}
		]},
		{gugun:"동해시", sub:[
{dong:"천곡동"}
,{dong:"평릉동"}
,{dong:"송정동"}
,{dong:"용정동"}
,{dong:"지흥동"}
,{dong:"효가동"}
,{dong:"동회동"}
,{dong:"나안동"}
,{dong:"쇄운동"}
,{dong:"발한동"}
,{dong:"북평동"}
,{dong:"구미동"}
,{dong:"추암동"}
,{dong:"구호동"}
,{dong:"단봉동"}
,{dong:"지가동"}
,{dong:"이도동"}
,{dong:"귀운동"}
,{dong:"호현동"}
,{dong:"내동"}
,{dong:"묵호진동"}
,{dong:"삼화동"}
,{dong:"이기동"}
,{dong:"이로동"}
,{dong:"어달동"}
,{dong:"대진동"}
,{dong:"망상동"}
,{dong:"초구동"}
,{dong:"괴란동"}
,{dong:"만우동"}
,{dong:"신흥동"}
,{dong:"비천동"}
,{dong:"달방동"}
		]},
		{gugun:"태백시", sub:[
{dong:"황지동"}
,{dong:"장성동"}
,{dong:"금천동"}
,{dong:"철암동"}
,{dong:"문곡동"}
,{dong:"동점동"}
,{dong:"소도동"}
,{dong:"혈동"}
,{dong:"화전동"}
,{dong:"창죽동"}
,{dong:"통동"}
,{dong:"백산동"}
,{dong:"원동"}
,{dong:"상사미동"}
,{dong:"하사미동"}
,{dong:"조탄동"}
		]},
		{gugun:"속초시", sub:[
{dong:"영랑동"}
,{dong:"동명동"}
,{dong:"중앙동"}
,{dong:"금호동"}
,{dong:"청학동"}
,{dong:"교동"}
,{dong:"노학동"}
,{dong:"조양동"}
,{dong:"청호동"}
,{dong:"도문동"}
,{dong:"설악동"}
,{dong:"장사동"}
		]},
		{gugun:"삼척시", sub:[
{dong:"성내동"}
,{dong:"성북동"}
,{dong:"읍상동"}
,{dong:"읍중동"}
,{dong:"당저동"}
,{dong:"교동"}
,{dong:"갈천동"}
,{dong:"증산동"}
,{dong:"우지동"}
,{dong:"자원동"}
,{dong:"평전동"}
,{dong:"등봉동"}
,{dong:"도경동"}
,{dong:"마평동"}
,{dong:"오사동"}
,{dong:"건지동"}
,{dong:"원당동"}
,{dong:"성남동"}
,{dong:"사직동"}
,{dong:"오분동"}
,{dong:"적노동"}
,{dong:"조비동"}
,{dong:"정상동"}
,{dong:"정하동"}
,{dong:"근산동"}
,{dong:"원덕읍"}
		]},
		{gugun:"영월군", sub:[
{dong:"상동읍"}
,{dong:"김삿갓면"}
,{dong:"한반도면"}
		]},
		{gugun:"정선군", sub:[
{dong:"고한읍"}
,{dong:"사북읍"}
,{dong:"신동읍"}
		]},
		{gugun:"철원군", sub:[
{dong:"김화읍"}
,{dong:"갈말읍"}
,{dong:"동송읍"}
		]},
		{gugun:"고성군", sub:[
{dong:"거진읍"}
		]},
		{gugun:"충주시", sub:[
{dong:"성내동"}
,{dong:"성남동"}
,{dong:"성서동"}
,{dong:"충인동"}
,{dong:"교현동"}
,{dong:"용산동"}
,{dong:"호암동"}
,{dong:"직동"}
,{dong:"단월동"}
,{dong:"가주동"}
,{dong:"용관동"}
,{dong:"용두동"}
,{dong:"달천동"}
,{dong:"봉방동"}
,{dong:"칠금동"}
,{dong:"연수동"}
,{dong:"목행동"}
,{dong:"종민동"}
,{dong:"안림동"}
,{dong:"목벌동"}
,{dong:"충의동"}
,{dong:"지현동"}
,{dong:"문화동"}
,{dong:"금릉동"}
,{dong:"수안보면"}
,{dong:"대소원면"}
,{dong:"중앙탑면"}
		]},
		{gugun:"제천시", sub:[
{dong:"의림동"}
,{dong:"서부동"}
,{dong:"동현동"}
,{dong:"남천동"}
,{dong:"교동"}
,{dong:"중앙로1가"}
,{dong:"중앙로2가"}
,{dong:"명동"}
,{dong:"화산동"}
,{dong:"하소동"}
,{dong:"신월동"}
,{dong:"청전동"}
,{dong:"모산동"}
,{dong:"고암동"}
,{dong:"장락동"}
,{dong:"흑석동"}
,{dong:"두학동"}
,{dong:"고명동"}
,{dong:"강제동"}
,{dong:"명지동"}
,{dong:"산곡동"}
,{dong:"왕암동"}
,{dong:"천남동"}
,{dong:"신동"}
,{dong:"자작동"}
,{dong:"대랑동"}
		]},
		{gugun:"보은군", sub:[
{dong:"속리산면"}
,{dong:"장안면"}
,{dong:"회인면"}
,{dong:"추풍령면"}
,{dong:"금왕읍"}
,{dong:"매포읍"}
		]},
		{gugun:"공주시", sub:[
{dong:"반죽동"}
,{dong:"봉황동"}
,{dong:"중학동"}
,{dong:"중동"}
,{dong:"산성동"}
,{dong:"교동"}
,{dong:"웅진동"}
,{dong:"금성동"}
,{dong:"옥룡동"}
,{dong:"봉정동"}
,{dong:"주미동"}
,{dong:"태봉동"}
,{dong:"오곡동"}
,{dong:"신기동"}
,{dong:"소학동"}
,{dong:"상왕동"}
,{dong:"무릉동"}
,{dong:"월송동"}
,{dong:"금흥동"}
,{dong:"쌍신동"}
,{dong:"월미동"}
,{dong:"검상동"}
,{dong:"석장리동"}
,{dong:"송선동"}
,{dong:"동현동"}
		]},
		{gugun:"보령시", sub:[
{dong:"대천동"}
,{dong:"죽정동"}
,{dong:"화산동"}
,{dong:"동대동"}
,{dong:"명천동"}
,{dong:"궁촌동"}
,{dong:"내항동"}
,{dong:"남곡동"}
,{dong:"요암동"}
		]},
		{gugun:"아산시", sub:[
{dong:"온천동"}
,{dong:"실옥동"}
,{dong:"방축동"}
,{dong:"기산동"}
,{dong:"초사동"}
,{dong:"신인동"}
,{dong:"법곡동"}
,{dong:"장존동"}
,{dong:"좌부동"}
,{dong:"풍기동"}
,{dong:"용화동"}
,{dong:"모종동"}
,{dong:"권곡동"}
,{dong:"배미동"}
,{dong:"득산동"}
,{dong:"점양동"}
,{dong:"신동"}
,{dong:"남동"}
,{dong:"배방읍"}
		]},
		{gugun:"서산시", sub:[
{dong:"읍내동"}
,{dong:"동문동"}
,{dong:"갈산동"}
,{dong:"온석동"}
,{dong:"잠홍동"}
,{dong:"수석동"}
,{dong:"석림동"}
,{dong:"석남동"}
,{dong:"예천동"}
,{dong:"양대동"}
,{dong:"오남동"}
,{dong:"장동"}
,{dong:"덕지천동"}
		]},
		{gugun:"논산시", sub:[
{dong:"화지동"}
,{dong:"반월동"}
,{dong:"대교동"}
,{dong:"부창동"}
,{dong:"취암동"}
,{dong:"등화동"}
,{dong:"지산동"}
,{dong:"덕지동"}
,{dong:"내동"}
,{dong:"관촉동"}
,{dong:"연무읍"}
		]},
		{gugun:"계룡시", sub:[
{dong:"금암동"}
,{dong:"엄사면"}
		]},
		{gugun:"당진시", sub:[
{dong:"읍내동"}
,{dong:"채운동"}
,{dong:"우두동"}
,{dong:"원당동"}
,{dong:"시곡동"}
,{dong:"수청동"}
,{dong:"대덕동"}
,{dong:"행정동"}
,{dong:"용연동"}
,{dong:"구룡동"}
,{dong:"송악읍"}
		]},
		{gugun:"서천군", sub:[
{dong:"서천읍"}
		]},
		{gugun:"홍성군", sub:[
{dong:"광천읍"}
		]},
		{gugun:"예산군", sub:[
{dong:"삽교읍"}
		]},
		{gugun:"천안시", sub:[
			{dong:"목천읍"}
			,{dong:"서리"}
			,{dong:"동리"}
			,{dong:"교촌리"}
			,{dong:"서흥리"}
			,{dong:"덕전리"}
			,{dong:"송전리"}
			,{dong:"석천리"}
			,{dong:"동평리"}
			,{dong:"운전리"}
			,{dong:"남화리"}
			,{dong:"지산리"}
			,{dong:"교천리"}
			,{dong:"신계리"}
			,{dong:"천정리"}
			,{dong:"응원리"}
			,{dong:"삼성리"}
			,{dong:"도장리"}
			,{dong:"소사리"}
			,{dong:"풍세면"}
			,{dong:"풍서리"}
			,{dong:"가송리"}
			,{dong:"미죽리"}
			,{dong:"두남리"}
			,{dong:"남관리"}
			,{dong:"삼태리"}
			,{dong:"용정리"}
			,{dong:"보성리"}
			,{dong:"광덕면"}
			,{dong:"광덕리"}
			,{dong:"지장리"}
			,{dong:"보산원리"}
			,{dong:"대덕리"}
			,{dong:"매당리"}
			,{dong:"신흥리"}
			,{dong:"무학리"}
			,{dong:"신덕리"}
			,{dong:"행정리"}
			,{dong:"대평리"}
			,{dong:"원덕리"}
			,{dong:"북면"}
			,{dong:"연춘리"}
			,{dong:"상동리"}
			,{dong:"은지리"}
			,{dong:"용암리"}
			,{dong:"매송리"}
			,{dong:"명덕리"}
			,{dong:"오곡리"}
			,{dong:"사담리"}
			,{dong:"전곡리"}
			,{dong:"양곡리"}
			,{dong:"납안리"}
			,{dong:"운용리"}
			,{dong:"대평리"}
			,{dong:"성남면"}
			,{dong:"신덕리"}
			,{dong:"봉양리"}
			,{dong:"대흥리"}
			,{dong:"대정리"}
			,{dong:"석곡리"}
			,{dong:"용원리"}
			,{dong:"신사리"}
			,{dong:"대화리"}
			,{dong:"화성리"}
			,{dong:"수신면"}
			,{dong:"속창리"}
			,{dong:"신풍리"}
			,{dong:"해정리"}
			,{dong:"백자리"}
			,{dong:"발산리"}
			,{dong:"장산리"}
			,{dong:"병천면"}
			,{dong:"가전리"}
			,{dong:"병천리"}
			,{dong:"탑원리"}
			,{dong:"도원리"}
			,{dong:"매성리"}
			,{dong:"관성리"}
			,{dong:"봉항리"}
			,{dong:"용두리"}
			,{dong:"송정리"}
			,{dong:"동면"}
			,{dong:"구도리"}
			,{dong:"송연리"}
			,{dong:"화계리"}
			,{dong:"광덕리"}
			,{dong:"동산리"}
			,{dong:"행암리"}
			,{dong:"덕성리"}
			,{dong:"죽계리"}
			,{dong:"장송리"}
			,{dong:"수남리"}
			,{dong:"화덕리"}
			,{dong:"대흥동"}
			,{dong:"사직동"}
			,{dong:"영성동"}
			,{dong:"오룡동"}
			,{dong:"성황동"}
			,{dong:"문화동"}
			,{dong:"원성동"}
			,{dong:"문화동"}
			,{dong:"원성동"}
			,{dong:"유량동"}
			,{dong:"원성동"}
			,{dong:"봉명동"}
			,{dong:"쌍용동"}
			,{dong:"다가동"}
			,{dong:"용곡동"}
			,{dong:"용곡동"}
			,{dong:"신방동"}
			,{dong:"구성동"}
			,{dong:"청수동"}
			,{dong:"삼룡동"}
			,{dong:"청당동"}
			,{dong:"구룡동"}
			,{dong:"원성동"}
			,{dong:"신부동"}
			,{dong:"안서동"}
			,{dong:"천안시서북구"}
			,{dong:"성환읍"}
			,{dong:"성환리"}
			,{dong:"성월리"}
			,{dong:"매주리"}
			,{dong:"율금리"}
			,{dong:"왕림리"}
			,{dong:"신방리"}
			,{dong:"송덕리"}
			,{dong:"우신리"}
			,{dong:"어룡리"}
			,{dong:"복모리"}
			,{dong:"신가리"}
			,{dong:"와룡리"}
			,{dong:"학정리"}
			,{dong:"대홍리"}
			,{dong:"수향리"}
			,{dong:"안궁리"}
			,{dong:"양령리"}
			,{dong:"도하리"}
			,{dong:"성거읍"}
			,{dong:"송남리"}
			,{dong:"천흥리"}
			,{dong:"오목리"}
			,{dong:"오색당리"}
			,{dong:"저리"}
			,{dong:"모전리"}
			,{dong:"삼곡리"}
			,{dong:"정촌리"}
			,{dong:"문덕리"}
			,{dong:"석교리"}
			,{dong:"요방리"}
			,{dong:"소우리"}
			,{dong:"신월리"}
			,{dong:"직산읍"}
			,{dong:"군동리"}
			,{dong:"군서리"}
			,{dong:"남산리"}
			,{dong:"판정리"}
			,{dong:"수헐리"}
			,{dong:"삼은리"}
			,{dong:"상덕리"}
			,{dong:"부송리"}
			,{dong:"모시리"}
			,{dong:"자은가리"}
			,{dong:"양당리"}
			,{dong:"신갈리"}
			,{dong:"마정리"}
			,{dong:"석곡리"}
			,{dong:"입장면"}
			,{dong:"하장리"}
			,{dong:"상장리"}
			,{dong:"기로리"}
			,{dong:"도림리"}
			,{dong:"양대리"}
			,{dong:"홍천리"}
			,{dong:"호당리"}
			,{dong:"시장리"}
			,{dong:"효계리"}
			,{dong:"신덕리"}
			,{dong:"신두리"}
			,{dong:"용정리"}
			,{dong:"흑암리"}
			,{dong:"산정리"}
			,{dong:"연곡리"}
			,{dong:"가산리"}
			,{dong:"유리"}
			,{dong:"독정리"}
			,{dong:"와촌동"}
			,{dong:"성정동"}
			,{dong:"성정동"}
			,{dong:"쌍용동"}
			,{dong:"쌍용동"}
			,{dong:"쌍용동"}
			,{dong:"백석동"}
			,{dong:"불당동"}
			,{dong:"두정동"}
			,{dong:"업성동"}
			,{dong:"신당동"}
			,{dong:"부대동"}
			,{dong:"두정동"}
			,{dong:"성성동"}
			,{dong:"차암동"}

		]},
		{gugun:"청양군", sub:[
			{dong:"청양읍"}
			,{dong:"읍내리"}
			,{dong:"백천리"}
			,{dong:"교월리"}
			,{dong:"벽천리"}
			,{dong:"적누리"}
			,{dong:"정좌리"}
			,{dong:"군량리"}
			,{dong:"장승리"}
			,{dong:"송방리"}
			,{dong:"청수리"}
			,{dong:"학당리"}
			,{dong:"운곡면"}
			,{dong:"위라리"}
			,{dong:"효제리"}
			,{dong:"후덕리"}
			,{dong:"모곡리"}
			,{dong:"신대리"}
			,{dong:"영양리"}
			,{dong:"미량리"}
			,{dong:"광암리"}
			,{dong:"추광리"}
			,{dong:"대치면"}
			,{dong:"주정리"}
			,{dong:"탄정리"}
			,{dong:"광금리"}
			,{dong:"구치리"}
			,{dong:"장곡리"}
			,{dong:"개곡리"}
			,{dong:"작천리"}
			,{dong:"광대리"}
			,{dong:"대치리"}
			,{dong:"오룡리"}
			,{dong:"형산리"}
			,{dong:"이화리"}
			,{dong:"시전리"}
			,{dong:"상갑리"}
			,{dong:"농소리"}
			,{dong:"수석리"}
			,{dong:"정산면"}
			,{dong:"서정리"}
			,{dong:"역촌리"}
			,{dong:"백곡리"}
			,{dong:"해남리"}
			,{dong:"남천리"}
			,{dong:"송학리"}
			,{dong:"대박리"}
			,{dong:"용두리"}
			,{dong:"마치리"}
			,{dong:"천장리"}
			,{dong:"내초리"}
			,{dong:"신덕리"}
			,{dong:"와촌리"}
			,{dong:"학암리"}
			,{dong:"덕성리"}
			,{dong:"광생리"}
			,{dong:"목면"}
			,{dong:"지곡리"}
			,{dong:"화양리"}
			,{dong:"신흥리"}
			,{dong:"안심리"}
			,{dong:"송암리"}
			,{dong:"본의리"}
			,{dong:"대평리"}
			,{dong:"청남면"}
			,{dong:"청소리"}
			,{dong:"지곡리"}
			,{dong:"내직리"}
			,{dong:"천내리"}
			,{dong:"동강리"}
			,{dong:"중산리"}
			,{dong:"왕진리"}
			,{dong:"인양리"}
			,{dong:"대흥리"}
			,{dong:"아산리"}
			,{dong:"상장리"}
			,{dong:"장평면"}
			,{dong:"중추리"}
			,{dong:"은곡리"}
			,{dong:"미당리"}
			,{dong:"적곡리"}
			,{dong:"락지리"}
			,{dong:"지천리"}
			,{dong:"죽림리"}
			,{dong:"화산리"}
			,{dong:"구룡리"}
			,{dong:"관현리"}
			,{dong:"분향리"}
			,{dong:"남양면"}
			,{dong:"구룡리"}
			,{dong:"신왕리"}
			,{dong:"백금리"}
			,{dong:"용마리"}
			,{dong:"대봉리"}
			,{dong:"흥산리"}
			,{dong:"매곡리"}
			,{dong:"온암리"}
			,{dong:"온직리"}
			,{dong:"용두리"}
			,{dong:"금정리"}
			,{dong:"봉암리"}
			,{dong:"화성면"}
			,{dong:"산정리"}
			,{dong:"장계리"}
			,{dong:"화강리"}
			,{dong:"농암리"}
			,{dong:"화암리"}
			,{dong:"기덕리"}
			,{dong:"수정리"}
			,{dong:"용당리"}
			,{dong:"신정리"}
			,{dong:"광평리"}
			,{dong:"매산리"}
			,{dong:"구재리"}
			,{dong:"비봉면"}
			,{dong:"록평리"}
			,{dong:"신원리"}
			,{dong:"중묵리"}
			,{dong:"사점리"}
			,{dong:"관산리"}
			,{dong:"장재리"}
			,{dong:"강정리"}
			,{dong:"양사리"}
			,{dong:"용천리"}
			,{dong:"방한리"}
			]},
		{gugun:"태안군", sub:[
{dong:"안면읍"}
		]},
		{gugun:"군산시", sub:[
{dong:"해망동"}
,{dong:"신흥동"}
,{dong:"금동"}
,{dong:"월명동"}
,{dong:"신창동"}
,{dong:"오룡동"}
,{dong:"금광동"}
,{dong:"신풍동"}
,{dong:"송풍동"}
,{dong:"삼학동"}
,{dong:"선양동"}
,{dong:"둔율동"}
,{dong:"창성동"}
,{dong:"명산동"}
,{dong:"송창동"}
,{dong:"개복동"}
,{dong:"중앙로1가"}
,{dong:"영화동"}
,{dong:"중앙로2가"}
,{dong:"영동"}
,{dong:"신영동"}
,{dong:"죽성동"}
,{dong:"평화동"}
,{dong:"중앙로3가"}
,{dong:"대명동"}
,{dong:"장재동"}
,{dong:"미원동"}
,{dong:"금암동"}
,{dong:"동흥남동"}
,{dong:"서흥남동"}
,{dong:"조촌동"}
,{dong:"경장동"}
,{dong:"경암동"}
,{dong:"구암동"}
,{dong:"내흥동"}
,{dong:"개정동"}
,{dong:"수송동"}
,{dong:"미장동"}
,{dong:"지곡동"}
,{dong:"나운동"}
,{dong:"미룡동"}
,{dong:"소룡동"}
,{dong:"오식도동"}
,{dong:"비응도동"}
,{dong:"신관동"}
,{dong:"산북동"}
,{dong:"내초동"}
		]},
		{gugun:"익산시", sub:[
{dong:"창인동1가"}
,{dong:"창인동2가"}
,{dong:"중앙동1가"}
,{dong:"중앙동2가"}
,{dong:"중앙동3가"}
,{dong:"평화동"}
,{dong:"갈산동"}
,{dong:"주현동"}
,{dong:"인화동1가"}
,{dong:"동산동"}
,{dong:"마동"}
,{dong:"남중동"}
,{dong:"모현동1가"}
,{dong:"모현동2가"}
,{dong:"송학동"}
,{dong:"목천동"}
,{dong:"만석동"}
,{dong:"현영동"}
,{dong:"신동"}
,{dong:"영등동"}
,{dong:"어양동"}
,{dong:"신흥동"}
,{dong:"금강동"}
,{dong:"석탄동"}
,{dong:"팔봉동"}
,{dong:"덕기동"}
,{dong:"석왕동"}
,{dong:"정족동"}
,{dong:"임상동"}
,{dong:"월성동"}
,{dong:"부송동"}
,{dong:"용제동"}
,{dong:"석암동"}
		]},
		{gugun:"정읍시", sub:[
{dong:"수성동"}
,{dong:"장명동"}
,{dong:"상동"}
,{dong:"시기동"}
,{dong:"연지동"}
,{dong:"농소동"}
,{dong:"하모동"}
,{dong:"상평동"}
,{dong:"과교동"}
,{dong:"진산동"}
,{dong:"금붕동"}
,{dong:"송산동"}
,{dong:"신월동"}
,{dong:"용산동"}
,{dong:"교암동"}
,{dong:"부전동"}
,{dong:"쌍암동"}
,{dong:"내장동"}
,{dong:"하북동"}
,{dong:"구룡동"}
,{dong:"흑암동"}
,{dong:"용계동"}
,{dong:"공평동"}
,{dong:"망제동"}
,{dong:"신정동"}
		]},
		{gugun:"남원시", sub:[
{dong:"동충동"}
,{dong:"하정동"}
,{dong:"죽항동"}
,{dong:"쌍교동"}
,{dong:"천거동"}
,{dong:"금동"}
,{dong:"조산동"}
,{dong:"왕정동"}
,{dong:"신정동"}
,{dong:"향교동"}
,{dong:"용정동"}
,{dong:"광치동"}
,{dong:"내척동"}
,{dong:"산곡동"}
,{dong:"도통동"}
,{dong:"월락동"}
,{dong:"고죽동"}
,{dong:"식정동"}
,{dong:"노암동"}
,{dong:"어현동"}
,{dong:"신촌동"}
		]},
		{gugun:"김제시", sub:[
{dong:"요촌동"}
,{dong:"신풍동"}
,{dong:"용동"}
,{dong:"검산동"}
,{dong:"순동"}
,{dong:"백학동"}
,{dong:"서암동"}
,{dong:"신곡동"}
,{dong:"교동"}
,{dong:"갈공동"}
,{dong:"하동"}
,{dong:"흥사동"}
,{dong:"상동동"}
,{dong:"월성동"}
,{dong:"황산동"}
,{dong:"난봉동"}
,{dong:"오정동"}
,{dong:"복죽동"}
,{dong:"장화동"}
,{dong:"신덕동"}
,{dong:"월봉동"}
,{dong:"신월동"}
,{dong:"연정동"}
,{dong:"명덕동"}
,{dong:"제월동"}
,{dong:"도장동"}
,{dong:"서정동"}
		]},
		{gugun:"완주군", sub:[
{dong:"봉동읍"}
,{dong:"용진읍"}
		]},
		{gugun:"장수군", sub:[
{dong:"장계면"}
		]},
		{gugun:"임실군", sub:[
{dong:"오수면"}
		]},
		{gugun:"목포시", sub:[
{dong:"용당동"}
,{dong:"산정동"}
,{dong:"연산동"}
,{dong:"대성동"}
,{dong:"양동"}
,{dong:"북교동"}
,{dong:"남교동"}
,{dong:"호남동"}
,{dong:"대안동"}
,{dong:"명륜동"}
,{dong:"죽동"}
,{dong:"무안동"}
,{dong:"측후동"}
,{dong:"상락동1가"}
,{dong:"상락동2가"}
,{dong:"복만동"}
,{dong:"동명동"}
,{dong:"광동1가"}
,{dong:"광동3가"}
,{dong:"영해동1가"}
,{dong:"영해동2가"}
,{dong:"행복동1가"}
,{dong:"행복동2가"}
,{dong:"축복동1가"}
,{dong:"축복동2가"}
,{dong:"축복동3가"}
,{dong:"보광동1가"}
,{dong:"보광동3가"}
,{dong:"유달동"}
,{dong:"대의동1가"}
,{dong:"대의동2가"}
,{dong:"대의동3가"}
,{dong:"중앙동1가"}
,{dong:"중앙동2가"}
,{dong:"중앙동3가"}
,{dong:"만호동"}
,{dong:"수강동2가"}
,{dong:"해안동1가"}
,{dong:"해안동2가"}
,{dong:"해안동3가"}
,{dong:"해안동4가"}
,{dong:"항동"}
,{dong:"중동1가"}
,{dong:"중동2가"}
,{dong:"유동"}
,{dong:"금동2가"}
,{dong:"경동1가"}
,{dong:"경동2가"}
,{dong:"서산동"}
,{dong:"금화동"}
,{dong:"온금동"}
,{dong:"죽교동"}
,{dong:"상동"}
,{dong:"용해동"}
,{dong:"달동"}
,{dong:"율도동"}
,{dong:"대양동"}
,{dong:"옥암동"}
		]},
		{gugun:"여수시", sub:[
{dong:"종화동"}
,{dong:"수정동"}
,{dong:"공화동"}
,{dong:"관문동"}
,{dong:"고소동"}
,{dong:"동산동"}
,{dong:"중앙동"}
,{dong:"교동"}
,{dong:"군자동"}
,{dong:"연등동"}
,{dong:"광무동"}
,{dong:"서교동"}
,{dong:"봉강동"}
,{dong:"봉산동"}
,{dong:"남산동"}
,{dong:"국동"}
,{dong:"신월동"}
,{dong:"여서동"}
,{dong:"오림동"}
,{dong:"미평동"}
,{dong:"둔덕동"}
,{dong:"오천동"}
,{dong:"만흥동"}
,{dong:"덕충동"}
,{dong:"경호동"}
,{dong:"학동"}
,{dong:"학용동"}
,{dong:"소호동"}
,{dong:"시전동"}
,{dong:"신기동"}
,{dong:"웅천동"}
,{dong:"선원동"}
,{dong:"여천동"}
,{dong:"화장동"}
,{dong:"주삼동"}
,{dong:"봉계동"}
,{dong:"화치동"}
,{dong:"월하동"}
,{dong:"평여동"}
,{dong:"중흥동"}
,{dong:"적량동"}
,{dong:"월내동"}
,{dong:"묘도동"}
,{dong:"낙포동"}
,{dong:"신덕동"}
,{dong:"호명동"}
		]},
		{gugun:"순천시", sub:[
{dong:"삼거동"}
,{dong:"와룡동"}
,{dong:"영동"}
,{dong:"옥천동"}
,{dong:"행동"}
,{dong:"금곡동"}
,{dong:"매곡동"}
,{dong:"석현동"}
,{dong:"가곡동"}
,{dong:"조곡동"}
,{dong:"생목동"}
,{dong:"덕암동"}
,{dong:"연향동"}
,{dong:"풍덕동"}
,{dong:"남정동"}
,{dong:"인제동"}
,{dong:"저전동"}
,{dong:"장천동"}
,{dong:"중앙동"}
,{dong:"동외동"}
,{dong:"교량동"}
,{dong:"대룡동"}
,{dong:"홍내동"}
,{dong:"오천동"}
,{dong:"덕월동"}
,{dong:"야흥동"}
,{dong:"인월동"}
,{dong:"대대동"}
,{dong:"왕지동"}
,{dong:"조례동"}
		]},
		{gugun:"나주시", sub:[
{dong:"토계동"}
,{dong:"송월동"}
,{dong:"안창동"}
,{dong:"삼영동"}
,{dong:"교동"}
,{dong:"서내동"}
,{dong:"산정동"}
,{dong:"경현동"}
,{dong:"보산동"}
,{dong:"금성동"}
,{dong:"남내동"}
,{dong:"과원동"}
,{dong:"성북동"}
,{dong:"중앙동"}
,{dong:"대호동"}
,{dong:"송촌동"}
,{dong:"석현동"}
,{dong:"청동"}
,{dong:"죽림동"}
,{dong:"삼도동"}
,{dong:"영산동"}
,{dong:"용산동"}
,{dong:"관정동"}
,{dong:"평산동"}
,{dong:"부덕동"}
,{dong:"이창동"}
,{dong:"대기동"}
,{dong:"동수동"}
,{dong:"오량동"}
,{dong:"진포동"}
,{dong:"빛가람동"}
		]},
		{gugun:"광양시", sub:[
{dong:"황금동"}
,{dong:"황길동"}
,{dong:"도이동"}
,{dong:"성황동"}
,{dong:"중군동"}
,{dong:"중동"}
,{dong:"마동"}
,{dong:"광영동"}
,{dong:"태인동"}
		]},
		{gugun:"고흥군", sub:[
{dong:"도양읍"}
		]},
		{gugun:"보성군", sub:[
{dong:"벌교읍"}
		]},
		{gugun:"장흥군", sub:[
{dong:"관산읍"}
,{dong:"대덕읍"}
		]},
		{gugun:"영암군", sub:[
{dong:"삼호읍"}
		]},
		{gugun:"무안군", sub:[
{dong:"일로읍"}
,{dong:"삼향읍"}
		]},
		{gugun:"영광군", sub:[
{dong:"백수읍"}
,{dong:"홍농읍"}
		]},
		{gugun:"완도군", sub:[
{dong:"금일읍"}
,{dong:"노화읍"}
		]},
		{gugun:"신안군", sub:[
{dong:"압해읍"}
		]},
		{gugun:"경주시", sub:[
{dong:"동부동"}
,{dong:"서부동"}
,{dong:"북부동"}
,{dong:"성동동"}
,{dong:"황오동"}
,{dong:"노동동"}
,{dong:"노서동"}
,{dong:"성건동"}
,{dong:"사정동"}
,{dong:"교동"}
,{dong:"인왕동"}
,{dong:"탑동"}
,{dong:"충효동"}
,{dong:"서악동"}
,{dong:"효현동"}
,{dong:"광명동"}
,{dong:"동방동"}
,{dong:"도지동"}
,{dong:"배반동"}
,{dong:"구황동"}
,{dong:"보문동"}
,{dong:"황성동"}
,{dong:"용강동"}
,{dong:"동천동"}
,{dong:"평동"}
,{dong:"조양동"}
,{dong:"시동"}
,{dong:"구정동"}
,{dong:"마동"}
,{dong:"하동"}
,{dong:"진현동"}
,{dong:"천군동"}
,{dong:"신평동"}
,{dong:"덕동"}
,{dong:"암곡동"}
,{dong:"황용동"}
,{dong:"손곡동"}
,{dong:"율동"}
,{dong:"배동"}
,{dong:"석장동"}
,{dong:"안강읍"}
,{dong:"건천읍"}
,{dong:"외동읍"}
		]},
		{gugun:"김천시", sub:[
{dong:"감호동"}
,{dong:"용두동"}
,{dong:"모암동"}
,{dong:"성내동"}
,{dong:"평화동"}
,{dong:"남산동"}
,{dong:"황금동"}
,{dong:"신음동"}
,{dong:"교동"}
,{dong:"문당동"}
,{dong:"다수동"}
,{dong:"백옥동"}
,{dong:"부곡동"}
,{dong:"지좌동"}
,{dong:"덕곡동"}
,{dong:"대광동"}
,{dong:"응명동"}
,{dong:"양천동"}
		]},
		{gugun:"안동시", sub:[
{dong:"삼산동"}
,{dong:"서부동"}
,{dong:"북문동"}
,{dong:"명륜동"}
,{dong:"신안동"}
,{dong:"율세동"}
,{dong:"옥정동"}
,{dong:"신세동"}
,{dong:"법흥동"}
,{dong:"동문동"}
,{dong:"동부동"}
,{dong:"운흥동"}
,{dong:"천리동"}
,{dong:"남부동"}
,{dong:"남문동"}
,{dong:"안흥동"}
,{dong:"대석동"}
,{dong:"옥야동"}
,{dong:"당북동"}
,{dong:"태화동"}
,{dong:"화성동"}
,{dong:"목성동"}
,{dong:"법상동"}
,{dong:"금곡동"}
,{dong:"평화동"}
,{dong:"안기동"}
,{dong:"운안동"}
,{dong:"상아동"}
,{dong:"안막동"}
,{dong:"옥동"}
,{dong:"이천동"}
,{dong:"노하동"}
,{dong:"송현동"}
,{dong:"송천동"}
,{dong:"석동동"}
,{dong:"정상동"}
,{dong:"수상동"}
,{dong:"수하동"}
		]},
		{gugun:"구미시", sub:[
{dong:"원평동"}
,{dong:"지산동"}
,{dong:"도량동"}
,{dong:"봉곡동"}
,{dong:"부곡동"}
,{dong:"선기동"}
,{dong:"수점동"}
,{dong:"남통동"}
,{dong:"형곡동"}
,{dong:"신평동"}
,{dong:"비산동"}
,{dong:"공단동"}
,{dong:"광평동"}
,{dong:"사곡동"}
,{dong:"상모동"}
,{dong:"임은동"}
,{dong:"오태동"}
,{dong:"신동"}
,{dong:"황상동"}
,{dong:"인의동"}
,{dong:"진평동"}
,{dong:"시미동"}
,{dong:"임수동"}
,{dong:"양호동"}
,{dong:"거의동"}
,{dong:"옥계동"}
,{dong:"구포동"}
,{dong:"고아읍"}
		]},
		{gugun:"영주시", sub:[
{dong:"영주동"}
,{dong:"상망동"}
,{dong:"하망동"}
,{dong:"휴천동"}
,{dong:"가흥동"}
,{dong:"문정동"}
,{dong:"고현동"}
,{dong:"창진동"}
,{dong:"상줄동"}
,{dong:"조암동"}
,{dong:"적서동"}
,{dong:"아지동"}
		]},
		{gugun:"영천시", sub:[
{dong:"조교동"}
,{dong:"망정동"}
,{dong:"야사동"}
,{dong:"문내동"}
,{dong:"문외동"}
,{dong:"창구동"}
,{dong:"교촌동"}
,{dong:"과전동"}
,{dong:"성내동"}
,{dong:"도동"}
,{dong:"금노동"}
,{dong:"완산동"}
,{dong:"범어동"}
,{dong:"작산동"}
,{dong:"봉동"}
,{dong:"본촌동"}
,{dong:"채신동"}
,{dong:"괴연동"}
,{dong:"녹전동"}
,{dong:"도림동"}
,{dong:"오미동"}
,{dong:"오수동"}
,{dong:"쌍계동"}
,{dong:"도남동"}
,{dong:"매산동"}
,{dong:"언하동"}
,{dong:"신기동"}
		]},
		{gugun:"상주시", sub:[
{dong:"성하동"}
,{dong:"성동동"}
,{dong:"인봉동"}
,{dong:"복룡동"}
,{dong:"냉림동"}
,{dong:"서성동"}
,{dong:"남성동"}
,{dong:"서문동"}
,{dong:"무양동"}
,{dong:"개운동"}
,{dong:"신봉동"}
,{dong:"가장동"}
,{dong:"양촌동"}
,{dong:"지천동"}
,{dong:"오대동"}
,{dong:"흥각동"}
,{dong:"거동동"}
,{dong:"인평동"}
,{dong:"화개동"}
,{dong:"외답동"}
,{dong:"헌신동"}
,{dong:"병성동"}
,{dong:"도남동"}
,{dong:"낙상동"}
,{dong:"중덕동"}
,{dong:"초산동"}
,{dong:"화산동"}
,{dong:"부원동"}
,{dong:"죽전동"}
,{dong:"만산동"}
,{dong:"연원동"}
,{dong:"남장동"}
,{dong:"남적동"}
		]},
		{gugun:"문경시", sub:[
{dong:"점촌동"}
,{dong:"영신동"}
,{dong:"흥덕동"}
,{dong:"우지동"}
,{dong:"창동"}
,{dong:"신기동"}
,{dong:"불정동"}
,{dong:"유곡동"}
,{dong:"공평동"}
,{dong:"윤직동"}
,{dong:"가은읍"}
		]},
		{gugun:"경산시", sub:[
{dong:"삼남동"}
,{dong:"삼북동"}
,{dong:"서상동"}
,{dong:"신교동"}
,{dong:"상방동"}
,{dong:"백천동"}
,{dong:"옥곡동"}
,{dong:"사정동"}
,{dong:"옥산동"}
,{dong:"정평동"}
,{dong:"대평동"}
,{dong:"대정동"}
,{dong:"임당동"}
,{dong:"대동"}
,{dong:"계양동"}
,{dong:"중방동"}
,{dong:"조영동"}
,{dong:"남방동"}
,{dong:"여천동"}
,{dong:"유곡동"}
,{dong:"신천동"}
,{dong:"점촌동"}
,{dong:"평산동"}
,{dong:"사동"}
,{dong:"삼풍동"}
,{dong:"갑제동"}
,{dong:"진량읍"}
		]},
		{gugun:"청도군", sub:[
{dong:"청도읍"}
		]},
		{gugun:"고령군", sub:[
{dong:"대가야읍"}
		]},
		{gugun:"칠곡군", sub:[
{dong:"북삼읍"}
,{dong:"석적읍"}
		]},
		{gugun:"울진군", sub:[
{dong:"평해읍"}
		]},
		{gugun:"진주시", sub:[
{dong:"망경동"}
,{dong:"주약동"}
,{dong:"강남동"}
,{dong:"칠암동"}
,{dong:"본성동"}
,{dong:"동성동"}
,{dong:"남성동"}
,{dong:"인사동"}
,{dong:"대안동"}
,{dong:"중안동"}
,{dong:"계동"}
,{dong:"봉곡동"}
,{dong:"상봉동"}
,{dong:"봉래동"}
,{dong:"수정동"}
,{dong:"장대동"}
,{dong:"옥봉동"}
,{dong:"상대동"}
,{dong:"상평동"}
,{dong:"초전동"}
,{dong:"장재동"}
,{dong:"하촌동"}
,{dong:"신안동"}
,{dong:"평거동"}
,{dong:"이현동"}
,{dong:"유곡동"}
,{dong:"판문동"}
,{dong:"가좌동"}
,{dong:"호탄동"}
,{dong:"충무공동"}
		]},
		{gugun:"통영시", sub:[
{dong:"도천동"}
,{dong:"서호동"}
,{dong:"명정동"}
,{dong:"항남동"}
,{dong:"중앙동"}
,{dong:"문화동"}
,{dong:"태평동"}
,{dong:"동호동"}
,{dong:"정량동"}
,{dong:"무전동"}
,{dong:"평림동"}
,{dong:"인평동"}
,{dong:"당동"}
,{dong:"미수동"}
,{dong:"봉평동"}
,{dong:"도남동"}
		]},
		{gugun:"사천시", sub:[
{dong:"동동"}
,{dong:"서동"}
,{dong:"선구동"}
,{dong:"동금동"}
,{dong:"서금동"}
,{dong:"동림동"}
,{dong:"좌룡동"}
,{dong:"벌리동"}
,{dong:"용강동"}
,{dong:"봉남동"}
,{dong:"이금동"}
,{dong:"이홀동"}
,{dong:"궁지동"}
,{dong:"사등동"}
,{dong:"향촌동"}
,{dong:"대방동"}
,{dong:"실안동"}
,{dong:"마도동"}
,{dong:"신수동"}
,{dong:"백천동"}
,{dong:"신벽동"}
,{dong:"노룡동"}
,{dong:"대포동"}
,{dong:"송포동"}
,{dong:"죽림동"}
		]},
		{gugun:"김해시", sub:[
{dong:"동상동"}
,{dong:"서상동"}
,{dong:"부원동"}
,{dong:"봉황동"}
,{dong:"대성동"}
,{dong:"구산동"}
,{dong:"삼계동"}
,{dong:"내동"}
,{dong:"외동"}
,{dong:"풍유동"}
,{dong:"명법동"}
,{dong:"이동"}
,{dong:"화목동"}
,{dong:"전하동"}
,{dong:"강동"}
,{dong:"삼정동"}
,{dong:"어방동"}
,{dong:"삼방동"}
,{dong:"지내동"}
,{dong:"불암동"}
,{dong:"유하동"}
,{dong:"내덕동"}
,{dong:"부곡동"}
,{dong:"무계동"}
,{dong:"신문동"}
,{dong:"삼문동"}
,{dong:"대청동"}
,{dong:"율하동"}
,{dong:"장유동"}
,{dong:"응달동"}
,{dong:"수가동"}
		]},
		{gugun:"밀양시", sub:[
{dong:"내일동"}
,{dong:"내이동"}
,{dong:"교동"}
,{dong:"삼문동"}
,{dong:"남포동"}
,{dong:"용평동"}
,{dong:"활성동"}
,{dong:"가곡동"}
,{dong:"하남읍"}
		]},
		{gugun:"거제시", sub:[
{dong:"능포동"}
,{dong:"장승포동"}
,{dong:"두모동"}
,{dong:"아양동"}
,{dong:"아주동"}
,{dong:"옥포동"}
,{dong:"덕포동"}
,{dong:"장평동"}
,{dong:"고현동"}
,{dong:"문동동"}
,{dong:"삼거동"}
,{dong:"양정동"}
,{dong:"수월동"}
		]},
		{gugun:"양산시", sub:[
{dong:"다방동"}
,{dong:"남부동"}
,{dong:"중부동"}
,{dong:"북부동"}
,{dong:"명곡동"}
,{dong:"신기동"}
,{dong:"북정동"}
,{dong:"산막동"}
,{dong:"호계동"}
,{dong:"유산동"}
,{dong:"어곡동"}
,{dong:"용당동"}
,{dong:"삼호동"}
,{dong:"명동"}
,{dong:"주남동"}
,{dong:"소주동"}
,{dong:"주진동"}
,{dong:"평산동"}
,{dong:"매곡동"}
,{dong:"물금읍"}
		]},
		{gugun:"의령군", sub:[
{dong:"궁류면"}
		]},
		{gugun:"함안군", sub:[
{dong:"칠원읍"}
		]},
		{gugun:"창녕군", sub:[
{dong:"남지읍"}
		]},
		{gugun:"제주시", sub:[
{dong:"일도일동"}
,{dong:"일도이동"}
,{dong:"이도일동"}
,{dong:"이도이동"}
,{dong:"삼도일동"}
,{dong:"삼도이동"}
,{dong:"건입동"}
,{dong:"용담일동"}
,{dong:"용담이동"}
,{dong:"화북일동"}
,{dong:"화북이동"}
,{dong:"삼양일동"}
,{dong:"삼양이동"}
,{dong:"삼양삼동"}
,{dong:"봉개동"}
,{dong:"아라일동"}
,{dong:"아라이동"}
,{dong:"오라일동"}
,{dong:"오라삼동"}
,{dong:"노형동"}
,{dong:"외도일동"}
,{dong:"외도이동"}
,{dong:"이호일동"}
,{dong:"이호이동"}
,{dong:"도두일동"}
,{dong:"도두이동"}
,{dong:"도남동"}
,{dong:"도련이동"}
,{dong:"용강동"}
,{dong:"회천동"}
,{dong:"오등동"}
,{dong:"월평동"}
,{dong:"영평동"}
,{dong:"연동"}
,{dong:"도평동"}
,{dong:"해안동"}
,{dong:"애월읍"}
,{dong:"구좌읍"}
,{dong:"조천읍"}
		]},
		{gugun:"서귀포시", sub:[
{dong:"서귀동"}
,{dong:"법환동"}
,{dong:"서호동"}
,{dong:"호근동"}
,{dong:"동홍동"}
,{dong:"서홍동"}
,{dong:"상효동"}
,{dong:"하효동"}
,{dong:"신효동"}
,{dong:"토평동"}
,{dong:"중문동"}
,{dong:"회수동"}
,{dong:"대포동"}
,{dong:"월평동"}
,{dong:"강정동"}
,{dong:"도순동"}
,{dong:"하원동"}
,{dong:"색달동"}
,{dong:"하예동"}
,{dong:"영남동"}
,{dong:"남원읍"}
,{dong:"성산읍"}
		]}
];